 
<!DOCTYPE html>
<script src="http://code.jquery.com/jquery-1.9.1.min.js "></script>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>       
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
 
<div id="who-we-are" class="who-we-are-main-block"  >
    <div class="container">
      <div class="row">

        <div class="col-md-12">
          <div class="section">
            <h3 class="section-heading" style="color:#b3469a;text-align:center"> Your Customization</h3>


	  
 <?php $model = new Model_PlusData();    $model->_name  = 'hotels_imgs';   
                                          $where = array('id' => $_GET['category'] );
						        $toppages2c = $model->selectForArray($where, array('displayorder' => 'ASC')  );
								foreach($toppages2c as $index =>$item2c):	?>
<?php endforeach; ?>
 <div class="col-xs-12">
  <div class="col-xs-2">  </div>
  <div class="col-md-4"> 


          
          


 <?php $model = new Model_PlusData();    $model->_name  = 'stand';   
                                          $where = array('id' => $_GET['stand'] );
						        $toppages2 = $model->selectForArray($where, array('displayorder' => 'ASC')  );
								foreach($toppages2 as $index =>$item2):	?>

            <img  style="position: relative; z-index: 400;"src="<?php echo  APP_BASEURL.'/MyUpload/'.$item2->Img ?>" class="img-responsive" >
          <img  style="position: absolute;width: 153px;z-index: 0;top: 123px;left: 105px;" src="<?php echo  APP_BASEURL.'/MyUpload/'.$item2c->Img ?>"  >
  
          
<?php endforeach; ?>

</div>

   <div class="col-md-5" style="padding-top: 100px;     font-size: 40px;<?php if($_GET['font'] =='2'):?> font-family:Freestyle <?php elseif($_GET['font'] =='1'):?> font-family:cononet <?php elseif($_GET['font'] =='3'):?> font-family:PALSCRI <?php elseif($_GET['font'] =='4'):?> font-family:ITCEDSCR <?php elseif($_GET['font'] =='5'):?> font-family:BrushScript <?php endif; ?>"><?php echo $_GET['text'] ;?> </div>     
</div>


    <div class="col-xs-12" style="margin-top:70px;text-align: center;" >

   <div class="col-xs-12" style="padding-bottom: 20px;text-align: center;" >  <?php echo $this->siteData3['notes'] ?>   <?php echo $this->siteData3['time'] ?></div>

 <button  onclick="goBack()" type="submit" style="background-color: #b64f9d;color:#fff" class="btn"><span><< Back to Customization</span></button>
 <a    href="<?php echo  APP_BASEURL ?>/send/index?stand=<?php echo $_GET['stand']?>&font=<?php echo $_GET['font']?>&category=<?php echo $_GET['category']?>&text=<?php echo $_GET['text']?>" style="background-color: #b64f9d;color:#fff" class="btn"><span>Order Now >></span></a>

 	</div>
		<script>
function goBack() {
  window.history.back();
}
</script>
							
			 


 
               
          </div>
       </div>
         
      </div>
    </div>
  </div>

 



  

