 
 
  <script type="text/javascript" src="<?= $this->baseUrl(); ?>/ui/editor/tinymce/tiny_mce.js"></script>


   
<script type="text/javascript">
    tinyMCE.init({
            // General options
            //mode : "textareas",
            mode : "exact",
            elements : "elm1,elm2,elm3,elm4,elm5,elm6,elm7,elm8,elm9",
            language : "en",
            theme : "advanced",
            plugins : "openmanager,autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,autosave,visualblocks",
             
		// Theme options
		theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
		theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
		theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
		theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak,restoredraft,visualblocks,|,openmanager",
		theme_advanced_toolbar_location : "top",
		theme_advanced_toolbar_align : "left",
		theme_advanced_statusbar_location : "bottom",
		theme_advanced_resizing : true,
		
		//Open Manager Options
		file_browser_callback: "openmanager",
		open_manager_upload_path: '../../../../../MyUpload/',

		// Example content CSS (should be your site CSS)
		content_css : "css/content.css",

		// Drop lists for link/image/media/template dialogs
		template_external_list_url : "lists/template_list.js",
		external_link_list_url : "lists/link_list.js",
		external_image_list_url : "lists/image_list.js",
		media_external_list_url : "lists/media_list.js",

		// Style formats
		style_formats : [
			{title : 'Bold text', inline : 'b'},
			{title : 'Red text', inline : 'span', styles : {color : '#ff0000'}},
			{title : 'Red header', block : 'h1', styles : {color : '#ff0000'}},
			{title : 'Example 1', inline : 'span', classes : 'example1'},
			{title : 'Example 2', inline : 'span', classes : 'example2'},
			{title : 'Table styles'},
			{title : 'Table row 1', selector : 'tr', classes : 'tablerow1'}
		],

		// Replace values for the template plugin
		template_replace_values : {
			username : "Some User",
			staffid : "991234"
		}
	});
</script>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
            <img id="preview" height="300" width="575">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

<style>
    .tinymce body, td, pre
    {
        direction: rtl !important ;
    }

</style>


<h1> <?php echo $this->typename ?></h1>
 


<?php if($this->typename == 'Advertise' ): ?>
  <script src="https://code.jquery.com/jquery-1.10.2.js"></script>

 <script>
$( '#catid' ).attr( 'onchange' , 'myFunction()'  );
$( '#data5' ).attr( 'type' , 'hidden'  );
$( '#pageiditem' ).attr( 'type' , 'hidden'  );
</script>

<script>
function myFunction() {
 
    var pageidx = document.getElementById("catid");
    document.getElementById("data5").value = pageidx.options[pageidx.selectedIndex].text; 
    document.getElementById("pageiditem").value = (pageidx.options[pageidx.selectedIndex].text).split("-").pop();
}
</script>
  

 




 





<?php endif ?>
























<?php if($this->typename == 'Project Category' ): ?>

  <script src="https://code.jquery.com/jquery-1.10.2.js"></script>

 <script>
$( '#pageid' ).attr( 'onchange' , 'myFunction()'  );
$( '#data5' ).attr( 'type' , 'hidden'  );
</script>


<script type="text/javascript">

function myFunction() {

    var pageidx = document.getElementById("pageid");
    document.getElementById("data5").value = pageidx.options[pageidx.selectedIndex].text;
}
</script>

  <script type="text/javascript" src="<?=$this->baseUrl()?>/resources/scripts/jquery.Jcrop.js"></script>



<?php endif ?>





 <?php if($this->typename == 'Pages'  ): ?>
<?php $numpageid=  $this->serv2;  ?>




 <form role="form"  id="form" name="form2" method="post" action=""    enctype="multipart/form-data" >
 
 
 <?php echo $this->form->pageid ;  ?>
<?php echo $this->form->data5 ;  ?>
 
<?php echo $this->form->title ;  ?>

 <?php echo $this->form->type2 ;  ?>
<?php echo $this->form->decription ;  ?>
<?php echo $this->form->decription2 ;  ?>
<?php echo $this->form->pagurl ;  ?>
 
 <?php echo $this->form->save ;   ?>


</form>

 

  <script src="https://code.jquery.com/jquery-1.10.2.js"></script>

<script type="text/javascript">

        $( document ).ready(function() {
                $("select#pageid option").filter(function() {
                    return $(this).val() == <?php echo $numpageid;   ?>; 
                }).prop('selected', true);
var pageidx = document.getElementById("pageid");
    document.getElementById("data5").value = pageidx.options[pageidx.selectedIndex].text;

        });        
        </script>

 
 <script>
$( '#pageid' ).attr( 'onchange' , 'myFunction()'  );
$( '#data5' ).attr( 'type' , 'hidden'  );
document.getElementById("data5-label").style.display = "none";
</script> 


<script>
function myFunction() {
 
    var pageidx = document.getElementById("pageid");
    document.getElementById("data5").value = pageidx.options[pageidx.selectedIndex].text;
}
</script>



<?php endif ?>


<script type="text/javascript">
$(function() {
    $('#title').keyup(function() {
        var txtClone = $(this).val();
		 key=txtClone.replace(" ","-");
       replaced = key.split(' ').join('-');
        $('#pagurl').val(replaced);
    });
});
</script>


<?php if($this->typename == 'FAQ, Accordion Page Style'   || $this->typename == 'Page Style Contact Us'   ||   $this->typename == 'Page Style'): ?>
  <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
 <script>
$( '#pageid' ).attr( 'onchange' , 'myFunction()'  );
$( '#data5' ).attr( 'type' , 'hidden'  );
</script> 


<script>
function myFunction() {
 
    var pageidx = document.getElementById("pageid");
    document.getElementById("data5").value = pageidx.options[pageidx.selectedIndex].text;
}
</script>
<?php endif ?>  



 
