 
 
  <script type="text/javascript" src="<?= $this->baseUrl(); ?>/ui/editor/tinymce/tiny_mce.js"></script>


   
<script type="text/javascript">
    tinyMCE.init({
            // General options
            //mode : "textareas",
            mode : "exact",
            elements : "elm1,elm2,elm3,elm4,elm5,elm6,elm7,elm8,elm9",
            language : "en",
            theme : "advanced",
            plugins : "openmanager,autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,autosave,visualblocks",
             
		// Theme options
		theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
		theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
		theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
		theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak,restoredraft,visualblocks,|,openmanager",
		theme_advanced_toolbar_location : "top",
		theme_advanced_toolbar_align : "left",
		theme_advanced_statusbar_location : "bottom",
		theme_advanced_resizing : true,
		
		//Open Manager Options
		file_browser_callback: "openmanager",
		open_manager_upload_path: '../../../../../MyUpload/',

		// Example content CSS (should be your site CSS)
		content_css : "css/content.css",

		// Drop lists for link/image/media/template dialogs
		template_external_list_url : "lists/template_list.js",
		external_link_list_url : "lists/link_list.js",
		external_image_list_url : "lists/image_list.js",
		media_external_list_url : "lists/media_list.js",

		// Style formats
		style_formats : [
			{title : 'Bold text', inline : 'b'},
			{title : 'Red text', inline : 'span', styles : {color : '#ff0000'}},
			{title : 'Red header', block : 'h1', styles : {color : '#ff0000'}},
			{title : 'Example 1', inline : 'span', classes : 'example1'},
			{title : 'Example 2', inline : 'span', classes : 'example2'},
			{title : 'Table styles'},
			{title : 'Table row 1', selector : 'tr', classes : 'tablerow1'}
		],

		// Replace values for the template plugin
		template_replace_values : {
			username : "Some User",
			staffid : "991234"
		}
	});
</script>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
            <img id="preview" height="300" width="575">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

<style>
    .tinymce body, td, pre
    {
        direction: rtl !important ;
    }

</style>


<h1> <?php echo $this->typename ?></h1>
 
 
 <?php  $id =$_GET['id']; ?> 

 

 
 <form role="form"  id="form" name="form2" method="post" action=""    enctype="multipart/form-data" >
 <?php echo $this->form->pageid ;  ?>
  <?php echo $this->form->type2 ;  ?>
 
<?php echo $this->form->title ;  ?>
<?php echo $this->form->titearabic ;  ?>
 
<?php echo $this->form->decription ;  ?>
<?php echo $this->form->decription2 ;  ?>

<?php echo $this->form->thumb ;  ?>
  
 


<?php echo $this->form->pagurl ;  ?>
 
 

<?php echo $this->form->save ;   ?>


</form>

 
 



<?php         $pageid = $_GET['id']; ?>

 








  <?php $numpageid=  $this->serv2;  ?>
<?php echo $numpageid; ?>

  
  <script src="https://code.jquery.com/jquery-1.10.2.js"></script>

<script type="text/javascript">

        $( document ).ready(function() {
                $("select#pageid option").filter(function() {
                    return $(this).val() == <?php echo $numpageid;   ?>; 
                }).prop('selected', true);
var pageidx = document.getElementById("pageid");
    document.getElementById("data5").value = pageidx.options[pageidx.selectedIndex].text;

        });        
        </script>

 
 <script>
$( '#pageid' ).attr( 'onchange' , 'myFunction()'  );
$( '#data5' ).attr( 'type' , 'hidden'  );
document.getElementById("data5-label").style.display = "none";
</script> 


<script>
function myFunction() {
 
    var pageidx = document.getElementById("pageid");
    document.getElementById("data5").value = pageidx.options[pageidx.selectedIndex].text;
}
</script>

 


<script type="text/javascript">
$(function() {
    $('#title').keyup(function() {
        var txtClone = $(this).val();
		 key=txtClone.replace(" ","-");
       replaced = key.split(' ').join('-');
        $('#pagurl').val(replaced);
    });
});
</script>


<?php if($this->typename == 'FAQ, Accordion Page Style'   || $this->typename == 'Page Style Contact Us'   ||   $this->typename == 'Page Style'): ?>
  <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
 <script>
$( '#pageid' ).attr( 'onchange' , 'myFunction()'  );
$( '#data5' ).attr( 'type' , 'hidden'  );
</script> 


<script>
function myFunction() {
 
    var pageidx = document.getElementById("pageid");
    document.getElementById("data5").value = pageidx.options[pageidx.selectedIndex].text;
}
</script>
<?php endif ?>  



  

  <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
 
  
<script type="text/javascript" src="<?php echo $this->themeUrl ?>js/jquery.ajup.js"></script>
 <script src="http://code.jquery.com/jquery-1.10.2.js"></script>
  <script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
 
  
<script type="text/javascript">

var imgs3 = new Array();

function showimgs3(){
 

    if(imgs3.length<=0){
        $('.imageuploader3 .files3').html("<div style=\"font-size: small;\">No image uploaded</div>");
        $('.image3').val('');
    }else{
        $('.imageuploader3 .files3').html("<table><tr>");
        $('.image3').val("");
        for (var i = 0; i < imgs3.length; i++) {
            // add file to the list
            $('.imageuploader3 .files3').html($('.imageuploader3 .files3').html()+"<div > <a href='javascript:removeimg3("+i+");'>Remove</a><br /> <img src='<?php echo $this->baseUrl() ?>/files/ful/i/"+imgs3[i]+"'     width='200' height='41'></img>      </div>");
            $('.image3').val($('.image3').val()+''+imgs3[i]);
        }
    }
}


  
function removeimg3(id){
    imgs3.splice(id,1);
    showimgs3();
  
}

 (function($){
               
        var button3 = '<div class="imageuploader3"> <a class="btn btn-danger" href="<?php echo  $this->baseUrl();?>/admin/cropthumb?widthw=1600&heighth=330&id=<?php echo $id ?>&tt=pages&ff=thumb&countryid=0"> Upload Headr Image </a><div style="display:none" class=" "><div id="button3" class="btn btn-danger" ><button class="btn btn-danger"> Add Photo</button></div></div>   <input id="content3" type="hidden" class="image3" style="width: 250px;" name="thumb" value="<?php echo $this->form->getElement('thumb')->getValue(); ?>" /><div class="files3" style="cursor:pointer"  id="sortable3" ></div>  </div>';
      $('#thumb').replaceWith(button3);
      if($('#button3').length){
         var button3 = $('#button3'), interval;    
         new AjaxUpload(button3, {
             action: '<?php echo $this->baseUrl().'/admin/upload/photo3'?>', 
             name: 'img3',
             onSubmit : function(file, ext){
                 if (ext && /^(jpg|jpeg|gif|png)$/i.test(ext)){
                     // change button text, when user selects file            
                 button3.text('upload process');
                                 
                 // If you want to allow uploading only 1 file at time,
                 // you can disable upload button
                 this.disable();
                 
                 // Uploding -> Uploading. -> Uploading...
                 interval = window.setInterval(function(){
                     var text = button3.text();
                     if (text.length < 13){
                         button3.text(text + '.');                    
                     } else {
                         button3.text('upload till process.........');                
                     }
                 }, 200);
                     
                 } else {
                     // cancel upload
                     alert("  image extention allow");
                     return false;                
                 }
             },
             onComplete: function(file, response){
                 button3.text('Upload new PDF');
                       
                 window.clearInterval(interval);
                             
                 // enable upload button
                 this.enable();
                 imgs3.splice(response);
                 imgs3.push( response );
                 showimgs3();
             }
         });
         if($('.image3').val()!=''){
             imgs3=$('.image3').val().split(' ');
                   
             for (var i = 0; i < imgs3.length; i++) {
                 if(imgs3[i]==''){
                     imgs3.splice(i,1);
                     i=i-1;
                 }
             }
         }
         showimgs3();
 
     }
 })(jQuery);
//-->

                  
    

 </script>
