<h1><?php echo $this->typename ?></h1>
<h4> <i class="fa fa-files-o"></i><a href="<?php echo constant('APP_BASEURL') .  '/admin/items7/createitem7' ?> "> Add New </a>  <spam style="margin-left: 40px;">   <i class="fa fa-files-o"></i> <a href="<?php echo constant('APP_BASEURL') .  '/admin/items7/indexitem7' ?>"> Update Existing </a>  </spam> </h4> 


<?php  if($this->Custom == 'items7')
{
    $form = $this->form;
    $form->setAction($this->baseUrl().'/admin/items7/search');
    $form->getElement('save')->setLabel('Search'); 
?>
 
<div class="formAk" >
     <form action="<?php echo $this->baseUrl() ?>/admin/items7/search" for="" class="" method="get" id="">
      <table width="400px" border="0">
  <tr>
     <td style="padding-right:20px" ><?php echo $this->form->regionid ;  ?></td>
    <td><?php echo $this->form->countryid ;  ?></td>
  </tr>

 

</table>   
        <input  style="margin-top:10px;"  type="submit" class="buttons" value="Search" id="save" name="save">
    </form>
</div>

<?php    
}
?>

<script type="text/javascript">
<!--
	(function($){
		 
                
               
                
                $('select[name="regionid"]').change(function(){
                    var form = $(this).parents('form').first();
                    
                    var region1 = form.find('select[name="countryid"]');
                    var prevVal = region1.find('option[selected]').attr('value');
                    region1.html('');
                    region1.attr('disabled','disabled');
                    region1.css('opacity','0.5');
                    
                    
                    var url = '<?php echo $this->baseUrl().'/admin/items/regions2' ?>';
 
                    var country = $(this).val();
                    region1.data('country', country);
                    if(!country)
                    {
                        var html = '<option value=""> ( ----------Select Country----------- ) </option>';
                        region1.html(html);
                        return;
                    }
                    
                    var data = {country: country};
                    $.ajax({
                            url:url,
                            data:data,
                            dataType:'json',
                            type:'POST',
                            success:function(data){
                                var html = '<option value=""> ( ----------Select Country-----------  ) </option>';
                                for(var i=0;i<data.length;i++)
                                    html = html + '<option value="'+data[i].id+'">'+data[i].region2+'</option>';
                                region1.html(html);
                                
                                region1.removeAttr('disabled');
                                region1.css('opacity','1');
                                region1.hide();
                                region1.fadeIn();
                                if($.QueryString['region1'])
                                    $('select[name="countryid"] option[value="'+$.QueryString['city']+'"]').attr('selected', 'selected');
                                
                                if(prevVal)
                                    region1.find('option[value="'+prevVal+'"]').attr('selected', 'selected');
                            }
                        });
                })
                $('select[name="regionid"]').change();
                
                (function($) {
                    $.QueryString = (function(a) {
                        if (a == "") return {};
                        var b = {};
                        for (var i = 0; i < a.length; ++i)
                        {
                            var p=a[i].split('=');
                            if (p.length != 2) continue;
                            b[p[0]] = decodeURIComponent(p[1].replace(/\+/g, " "));
                        }
                        return b;
                    })(window.location.search.substr(1).split('&'))
                })(jQuery);
                
                if($.QueryString['city'])
                    $('select[name="city"] option[value="'+$.QueryString['city']+'"]').attr('selected', 'selected').parent().change();
                
                if($.QueryString['category'])
                    $('select[name="category"] option[value="'+$.QueryString['category']+'"]').attr('selected', 'selected');

                if($.QueryString['category2'])
                    $('select[name="category2"] option[value="'+$.QueryString['category2']+'"]').attr('selected', 'selected');

                 if($.QueryString['category3'])
                    $('select[name="category3"] option[value="'+$.QueryString['category3']+'"]').attr('selected', 'selected');
                 
	})(jQuery);
//-->


</script>
    <script>
 document.getElementById("pageid-label" ).style.display = "none";
  $(function() {
    $( "#sortable" ).sortable();
    $( "#sortable" ).disableSelection();
  });
  </script>



<?php
$uri = $_SERVER["REQUEST_URI"];
$sortUrl = explode('/', $uri);
unset($sortUrl[count($sortUrl)-1]);
$sortUrl = implode('/', $sortUrl);
$sortUrl = $sortUrl . '/sort';
?>
<script type="text/javascript">
/* when the DOM is ready */
jQuery(document).ready(function() {
	/* grab important elements */
	var sortInput = jQuery('#sort_order');
	var submit = jQuery('#autoSubmit');
	var messageBox = jQuery('#message-box');
	var list = jQuery('#sortable');
	/* create requesting function to avoid duplicate code */
	var request = function(sortOrder) {
        console.log(sortOrder);
		jQuery.ajax({
			beforeSend: function() {
				messageBox.text('Updating the sort order in the database.');
			},
			complete: function() {
				location.reload();
			},
			data: {'sortOrder': sortOrder},
			type: 'post',
			url: '<?=$_SERVER["REQUEST_URI"]?>'
		});
	};
	/* worker function */
	var fnSubmit = function(save) {
		var sortOrder = [];
		list.children('tr').each(function(){
			sortOrder.push(jQuery(this).data('id'));
		});

		if(save) {
			request(sortOrder);
		}
	};
	/* store values */
	list.children('tr').each(function() {
		var tr = jQuery(this);
		tr.data('id',tr.attr('title')).attr('title','');
	});
	/* sortables */
	list.sortable({
		opacity: 0.7,
		update: function() {
			fnSubmit(true);
		}
	});
	list.disableSelection();
	/* ajax form submission */
	jQuery('#dd-form').bind('submit',function(e) {
		if(e) e.preventDefault();
		fnSubmit(true);
	});
});

</script>
 <?php  if(!empty($message)): ?>
    <div id="message-box"><?php echo $message; ?> Waiting for sortation submission...</div>
<?php endif; ?>
  
<form id="dd-form" action="<?php echo $_SERVER['REQUEST_URI']; ?>" method="post">
    <table  id="table1" class="table table-bordered table-striped dataTable">
        <thead>
            <tr >

                <?php
                foreach($this->listValue as $listValue)
                {
                    echo '<th>'.$listValue.'</th>';
                }
                ?>
                <th></th>
            </tr>
        </thead>
        <tbody  id="sortable">
            <?php $i = 1; foreach($this->paginator as $values) { ?>
            <tr  title="<?php  echo  !empty($values->id) ? $values->id : '' ?>"
                 id="<?php  echo  !empty($values->id) ? $values->id : '' ?>"
            >
                 <?php
                foreach($this->listValue as $key=>$listValue)
                {

                    echo '<td >';
                    $exm = explode(':', $key);
                    $type = reset($exm);
                    $variable = end($exm);
                    if($type == 'img')
                    {
                        echo $this->ImgView($values[$variable]);
                    }
                    elseif($type == 'DATE')
                    {
                        echo date("d-m-Y" ,$values[$variable]);
                    }
                    else
                    {
                        echo $values[$key];
                       $order[] = $values['id'];

                    }
                    echo '</td>';
                }
            ?>
                <td>
                  <a   style=" border: 1px;  border-style: double;  padding: 4px;"  href="<?php echo  $this->baseUrl();?>/admin/<?php echo $this->contName ?>/edititem7/id/<?php echo $values['id'] ?>?idpage=<?php echo $values['id'] ?>&countryid=<?php echo $values['countryid'] ?>" title="Edit">Edit</a>
                   
                     <?php
                    if($this->OffActions != 'delete')
                    {
                        if($values['id'] != 0)
                        {
                    ?>

                   <a style=" border: 1px;  border-style: double;  padding: 4px;" href="javascript:confdelete('<?php echo  $this->baseUrl();?>/admin/<?php echo $this->contName ?>/deleteitem7/id/<?php echo $values['id'] ?>')" title="Delete">Delet </a> 
                <?php
                        }
                    }
 
                ?>
                    
 

                </td>
            </tr>
          <?php $i++; } ?>
            
        </tbody>

    </table>
    <br>
  
 
   
    <div class="tablefooter clearfix">
  
         <?php echo $this->paginationControl($this->paginator,'Sliding','partials/pagination-control.phtml'); ?>
    </div>
 


 
 



 



<?php 

 if(isset($_POST['do_submit']))  {
	 $message = 'Sortation has been saved.'; 


}

?>

</form>


