<?php if($this->Custom == 'blocks1')
{
    $form = $this->form;
    $form->setAction($this->baseUrl().'/admin/cats/search');
    $form->getElement('save')->setLabel('Search'); 
?>
<h1> Filter BY Main Category</h1>
<div class="formAk" >
    <form action="<?php echo $this->baseUrl() ?>/admin/cats/search" for="" class="" method="get" id="">
        <?php echo $this->form->pageid ?>
        <input type="submit" class="buttons" value="Search" id="save" name="filter">
    </form>
</div>

<?php    
}elseif($this->Custom == 'items')
{
    $form = $this->form;
    $form->setAction($this->baseUrl().'/admin/items/search');
    $form->getElement('save')->setLabel('Search'); 
?>
<h1> Filter By Category</h1>
<div class="formAk" >
    <form action="<?php echo $this->baseUrl() ?>/admin/items/search" for="" class="" method="get" id="">
        <?php echo $this->form->catid ?>
        <input type="submit" class="buttons" value="Search" id="save" name="filter">
    </form>
</div>

<?php    
}
?>

<h1>Internal Page</h1>
    <script>
  $(function() {
    $( "#sortable" ).sortable();
    $( "#sortable" ).disableSelection();
  });
  </script>



<?php
$uri = $_SERVER["REQUEST_URI"];
$sortUrl = explode('/', $uri);
unset($sortUrl[count($sortUrl)-1]);
$sortUrl = implode('/', $sortUrl);
$sortUrl = $sortUrl . '/sort';
?>
<script type="text/javascript">
/* when the DOM is ready */
jQuery(document).ready(function() {
	/* grab important elements */
	var sortInput = jQuery('#sort_order');
	var submit = jQuery('#autoSubmit');
	var messageBox = jQuery('#message-box');
	var list = jQuery('#sortable');
	/* create requesting function to avoid duplicate code */
	var request = function(sortOrder) {
        console.log(sortOrder);
		jQuery.ajax({
			beforeSend: function() {
				messageBox.text('Updating the sort order in the database.');
			},
			complete: function() {
			     location.reload();
			},
			data: {'sortOrder': sortOrder},
			type: 'post',
			url: '<?=$_SERVER["REQUEST_URI"]?>'
		});
	};
	/* worker function */
	var fnSubmit = function(save) {
		var sortOrder = [];
		list.children('tr').each(function(){
			sortOrder.push(jQuery(this).data('id'));
		});

		if(save) {
			request(sortOrder);
		}
	};
	/* store values */
	list.children('tr').each(function() {
		var tr = jQuery(this);
		tr.data('id',tr.attr('title')).attr('title','');
	});
	/* sortables */
	list.sortable({
		opacity: 0.7,
		update: function() {
			fnSubmit(true);
		}
	});
	list.disableSelection();
	/* ajax form submission */
	jQuery('#dd-form').bind('submit',function(e) {
		if(e) e.preventDefault();
		fnSubmit(true);
	});
});

</script>
 <?php  if(!empty($message)): ?>
    <div id="message-box"><?php echo $message; ?> Waiting for sortation submission...</div>
<?php endif; ?>
  
<form id="dd-form" action="<?php echo $_SERVER['REQUEST_URI']; ?>" method="post">
    <table id="table1" class="table table-bordered table-striped dataTable">
        <thead>
            <tr >

                <?php
                foreach($this->listValue as $listValue)
                {
                    echo '<th>'.$listValue.'</th>';
                }
                ?>
                <th></th>
            </tr>
        </thead>
        <tbody  id="sortable">
            <?php $i = 1; foreach($this->paginator as $values) { ?>
            <tr  title="<?php  echo  !empty($values->id) ? $values->id : '' ?>"
                 id="<?php  echo  !empty($values->id) ? $values->id : '' ?>"
            >
                 <?php
                foreach($this->listValue as $key=>$listValue)
                {

                    echo '<td >';
                    $exm = explode(':', $key);
                    $type = reset($exm);
                    $variable = end($exm);
                    if($type == 'img')
                    {
                        echo $this->ImgView($values[$variable]);
                    }
                    elseif($type == 'DATE')
                    {
                        echo date("d-m-Y" ,$values[$variable]);
                    }
                    else
                    {
                        echo $values[$key];
                       $order[] = $values['id'];

                    }
                    echo '</td>';
                }
            ?>
                <td>
                  <a   style=" border: 1px;  border-style: double;  padding: 4px;"  href="<?php echo  $this->baseUrl();?>/admin/<?php echo $this->contName ?>/editinternalpage/id/<?php echo $values['id'] ?>?id=<?php echo $values['id'] ?>" title="Edit">Edit</a>
                   
                     <?php
                    if($this->OffActions != 'delete')
                    {
                 $list11 = array("0","84", "82", "2", "32", "34" , "24"); 
                        if(!in_array($values['id'], $list11))
                        {
                    ?>

                   <a style=" border: 1px;  border-style: double;  padding: 4px;" href="javascript:confdelete('<?php echo  $this->baseUrl();?>/admin/<?php echo $this->contName ?>/deleteinternalpage/id/<?php echo $values['id'] ?>')" title="Delete">Delet  </a> 
                <?php
                        }
                    }
 
                ?>
                    
 

                </td>
            </tr>
          <?php $i++; } ?>
            
        </tbody>

    </table>
    <br>
  
 
  <?php if($this->Custom !== 'contact' ): ?>
    <div class="tablefooter clearfix">
 
 
 
 <div class="actions">
            <a class="btn btn-primary" href="<?php echo $this->baseUrl(); ?>/admin/<?php echo $this->contName ?>/createinternalpage/serv/<?php echo $this->serv2;  ?>">Add New</a>
        </div>

         <?php echo $this->paginationControl($this->paginator,'Sliding','partials/pagination-control.phtml'); ?>
    </div>


 
             
 <?php endif; ?>


 
 



 



<?php 

 if(isset($_POST['do_submit']))  {
	 $message = 'Sortation has been saved.'; 


}

?>

</form>


