<?php  
 if(isset($_GET['restaurantID']))
{
   $restaurantID = $_GET['restaurantID'];
}
else{
$restaurantID = '';
}
 
?>
 




 
<h3 class="widget-title"><?php echo $this->typename ?> --   <spam style="color:red;" > <?php $model = new Model_PlusData();$model->_name  = 'Restaurants';
		           $toppages = $model->selectForArray(array('id' => $restaurantID), array('displayorder' => 'ASC'),1 ); 
                   foreach ($toppages  as  $toppage2 ){ echo $toppage2->Name; } ?> </spam></h3>
<div class="actions" style="margin-bottom:20px;" >
            <a class="btn btn-primary" href="<?php echo $this->baseUrl(); ?>/admin/<?php echo $this->contName ?>/createmenu?restaurantID=<?php echo $restaurantID; ?>">Add New</a>
        </div>

 



  

<?php
$uri = $_SERVER["REQUEST_URI"];
$sortUrl = explode('/', $uri);
unset($sortUrl[count($sortUrl)-1]);
$sortUrl = implode('/', $sortUrl);
$sortUrl = $sortUrl . '/sort';
?>

 

<script type="text/javascript">
/* when the DOM is ready */
jQuery(document).ready(function() {
	/* grab important elements */
	var sortInput = jQuery('#sort_order');
	var submit = jQuery('#autoSubmit');
	var messageBox = jQuery('#message-box');
	var list = jQuery('#sortable');
	/* create requesting function to avoid duplicate code */
	var request = function(sortOrder) {
        console.log(sortOrder);
		jQuery.ajax({
			beforeSend: function() {
				messageBox.text('Updating the sort order in the database.');
			},
			complete: function() {
				 location.reload();
			},
			data: {'sortOrder': sortOrder},
			type: 'post',
			url: '<?=$_SERVER["REQUEST_URI"]?>'
		});
	};
	/* worker function */
	var fnSubmit = function(save) {
		var sortOrder = [];
		list.children('tr').each(function(){
			sortOrder.push(jQuery(this).data('id'));
		});

		if(save) {
			request(sortOrder);
		}
	};
	/* store values */
	list.children('tr').each(function() {
		var tr = jQuery(this);
		tr.data('id',tr.attr('title')).attr('title','');
	});
	/* sortables */
	list.sortable({
		opacity: .7,

		update: function() {
			fnSubmit(true);
 
		}

	});
	list.disableSelection();
	/* ajax form submission */
	jQuery('#dd-form').bind('submit',function(e) {
		if(e) e.preventDefault();
		fnSubmit(true);
     

	});
});

</script>
   
<form id="dd-form" action="<?php echo $_SERVER['REQUEST_URI']; ?>" method="post">
 
   <table <?php if($this->Sort !== 'no'  ): ?>id="tableId" <?php endif; ?>  class="table table-bordered table-striped dataTable no-footer">
        <thead>
            <tr >
 <th ># </th> 
                <?php
                foreach($this->listValue as $listValue)
                {
                    echo '<th>'.$listValue.'</th>';
                }
                ?>
               <th></th>
            </tr>
        </thead>
 

        <tbody <?php if($this->Sort !== 'no'  ): ?>id="sortable" <?php endif; ?> class="ui-sortable">
            <?php $i = 1; foreach($this->paginator as $values) { ?>
<?php if(($values->RestaurantsID ) == $restaurantID): ?> 
            <tr  title="<?php  echo  !empty($values->id) ? $values->id : '' ?>"
                 id="<?php  echo  !empty($values->id) ? $values->id : '' ?>"
            >
 <td > <?php echo $i ?> </td> 
                 <?php
                foreach($this->listValue as $key=>$listValue)
                {

                    echo '<td >';
                    $exm = explode(':', $key);
                    $type = reset($exm);
                    $variable = end($exm);
                    if($type == 'img')
                    {
if($values[$variable] != '') {
                        echo $this->ImgView($values[$variable]);
}
                    }
                    elseif($type == 'DATE')
                    {
                        echo date("d-m-Y" ,$values[$variable]);
                    }
elseif($type == 'discount')
                    {
                        echo '$'.$values[$variable];
                    }

elseif($type == 'CategryID')
                    {
		           $model = new Model_PlusData();$model->_name  = 'FoodCategory';
		           $toppages = $model->selectForArray(array('id' => $values[$variable]), array('displayorder' => 'ASC'),1 ); 
                   foreach ($toppages  as  $toppage2 ){ echo $toppage2->Name; } 
                       
                    }

                    else
                    {
                        echo $values[$key];
                       $order[] = $values['id'];

                    }
                    echo '</td>';
                }
            ?>
                <td>





<?php $str = $this->Custom ;
$exclude_list = array("items3","items4" ,"items5"  , "Discounts") ;
?>

 
                  <a  class="badge badge-success"    href="<?php echo  $this->baseUrl();?>/admin/<?php echo $this->contName ?>/editmenu/id/<?php echo $values['id'] ?>?id=<?php echo $values['id'] ?>&restaurantID=<?php echo $values['RestaurantsID'] ?>" title="Edit">Edit</a>
    
                

                     <?php
                    if($this->OffActions != 'delete')
                    {
                        if($values['id'] != 0)
                        {
                    ?>

                   <a class="badge badge-danger"   href="javascript:confdelete('<?php echo  $this->baseUrl();?>/admin/<?php echo $this->contName ?>/deletemenu/id/<?php echo $values['id'] ?>&restaurantID=<?php echo $values['RestaurantsID'] ?>')" title="Delete">Delet </a> 
   

  

          
 
<?php
                        }
                    }
 
                ?>
                    
 

                </td>
            </tr>
<?php endif; ?> 
          <?php $i++; } ?>
            
        </tbody>

    </table>
    <br>
  
  
 



 



<?php 

 if(isset($_POST['do_submit']))  {
	 $message = 'Sortation has been saved.'; 


}

?>
  