 
<?php  foreach($this->Page as $value) : ?> 
<?php $idid = $value->id; ?>
 
		<div class="page-header">
			<div class="page-header__bg"
				style="background-image: url(<?php echo constant('APP_BASEURL').'/MyUpload/'.$value->Header; ?>);"></div>
			<!-- /.page-header__bg -->
			<div class="container">
				<ul class="thm-breadcrumb list-unstyled">
					<li><a href="<?php echo LANG_URL ?>index.php">Home</a></li>
					<li><?php echo $value->title; ?></li>
				</ul>
				<h2 class="page-header__title"><?php echo $value->title; ?> </h2><!-- /.page-header__title -->
			</div><!-- /.container -->
		</div><!-- /.page-header -->

<?php endforeach; ?>





 
<section class="about-four section-padding--top" style="margin-bottom:0px;    padding-top: 70px" >
			<div class="container">
				<div class="row gutter-y-60">
					<!-- <div class="col-lg-6">
						<div class="about-four__image" style="width: 90%;">
							<img  style="width: 100%;" src="<?php echo constant('APP_BASEURL').'/MyUpload/'.$value->Thumb; ?>" class="wow fadeInUp"
								data-wow-duration="1500ms" >
						</div>
					</div>  -->
					<div class="col-lg-12">
						<div class="about-four__content">
							<div class="section-title "> 
							<!--	<h2 class="section-title__title"><?php echo $value->title; ?></h2> --> <!-- /.section-title__title -->
							</div><!-- /.section-title -->
							<div class="about-four__text"><?php echo $value->Data; ?></div>
						 
						</div><!-- /.about-four__content -->
					</div><!-- /.col-lg-6 -->
				</div><!-- /.row -->
			</div><!-- /.container -->
		</section>
  
 


					
<!-- Sections -->
<?php $model = new Model_PlusData();    $model->_name  = 'PageSections';     $where = array('pageid' => ($value->id) , 'branche' => 'services'  );
						        $toppages = $model->selectForArray($where, array('displayorder' => 'ASC')  );
								foreach($toppages as $index =>$PageSections):	?>

 <?php if($PageSections->style == '1'): ?> 
  <div class="about-us-area ptb-0">


<section class="about-four section-padding--top">
			<div class="container">
				<div class="row gutter-y-60">
					<div class="col-lg-6">
						<div class="about-four__image">
							<img src="<?php echo constant('APP_BASEURL').'/MyUpload/'.$PageSections->Thumb; ?>" class="wow fadeInUp"
								data-wow-duration="1500ms" >
						</div><!-- /.about-four__image -->
					</div><!-- /.col-lg-6 -->
					<div class="col-lg-6">
						<div class="about-four__content">
							<div class="section-title "> 
								<h2 class="section-title__title"><?php echo $PageSections->title; ?></h2><!-- /.section-title__title -->
							</div><!-- /.section-title -->
							<div class="about-four__text"><?php echo $PageSections->description; ?></div>
						 
						</div><!-- /.about-four__content -->
					</div><!-- /.col-lg-6 -->
				</div><!-- /.row -->
			</div><!-- /.container -->
		</section>
             
    

<?php elseif($PageSections->style == '2'): ?> 
  <section class="about-four section-padding--top">
			<div class="container">
				<div class="row gutter-y-60">
			 
					<div class="col-lg-12">
						<div class="about-four__content">
							<div class="section-title "> 
								<h2 class="section-title__title"><?php echo $PageSections->title; ?></h2><!-- /.section-title__title -->
							</div><!-- /.section-title -->
							<div class="about-four__text"><?php echo $PageSections->description; ?></div>
						 
						</div><!-- /.about-four__content -->
					</div><!-- /.col-lg-6 -->
				</div><!-- /.row -->
			</div><!-- /.container -->
		</section>


<?php elseif($PageSections->style == '3'): ?>

  <section class="about-four section-padding--top">
			<div class="container">
				<div class="row gutter-y-60">
				
					<div class="col-lg-6">
						<div class="about-four__content">
							<div class="section-title "> 
								<h2 class="section-title__title"><?php echo $PageSections->title; ?></h2><!-- /.section-title__title -->
							</div><!-- /.section-title -->
							<div class="about-four__text"><?php echo $PageSections->description; ?></div>
						 
						</div><!-- /.about-four__content -->
					</div><!-- /.col-lg-6 -->

	<div class="col-lg-6">
						<div class="about-four__image">
							<img src="<?php echo constant('APP_BASEURL').'/MyUpload/'.$PageSections->Thumb; ?>" class="wow fadeInUp"
								data-wow-duration="1500ms" >
						</div><!-- /.about-four__image -->
					</div><!-- /.col-lg-6 -->
				</div><!-- /.row -->
			</div><!-- /.container -->
		</section>
 
<?php endif; ?>

<?php endforeach; ?>

