<?php $url = $this->baseUrl().'/admin/'; ?>
	<!-- Page header -->
			<div class="page-header page-header-light">
				<div class="page-header-content header-elements-md-inline">
					<div class="page-title d-flex">
						<h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">Home</span> - Dashboard</h4>
						<a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
					</div>

					<div class="header-elements d-none">
						<div class="d-flex justify-content-center">
						 		</div>
					</div>
				</div>

				<div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
					<div class="d-flex">
						<div class="breadcrumb">
							<a href="index.html" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
							<span class="breadcrumb-item active">Dashboard</span>
						</div>

						<a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
					</div>

					<div class="header-elements d-none">
						<div class="breadcrumb justify-content-center">
						 
						 
						</div>
					</div>
				</div>
			</div>
			<!-- /page header -->


			<!-- Content area -->
			<div class="content">

				<!-- Main charts -->
				<div class="row">
					<div class="col-xl-12">



	<div class="row">

 

							</div>
 






	<div class="col-lg-12">

<div class="card">

<div class="table-responsive">
								<table class="table text-nowrap">
							 
									<tbody>
 	
									

    


   



   



       

									</tbody>
								</table>
							</div>

				 

							
						</div>
</div>


						 
						</div>

						<!-- Traffic sources -->
						<div class="card" style="
    width: 100%;
">
							<div class="card-header header-elements-inline">
								<h6 class="card-title">Quick Link</h6>
							 
							</div>

							<div class="card-body py-0">

<div class="row">
							<div class="col-sm-4"> 	<!-- Available hours -->
								<div class="card text-center">
									<div class="card-body">
 	<!-- Progress counter -->
 
<a style="width: 120px; height: 120px; padding: 30px; font-size:15px;" href="<?php echo $url.'Pages/edit/id/1?id=1' ?>" class="btn bg-primary-400 rounded-round btn-icon btn-sm"><i class="icon-pencil"></i><br/>About Us</a>
   	</div>
								</div>
								<!-- /available hours -->

							</div>




 	<div class="col-sm-4"> 	<!-- Available hours -->
								<div class="card text-center">
									<div class="card-body">
 	<!-- Progress counter -->
 
<a style="background:#000;width: 120px; height: 120px; padding: 30px; font-size:15px;" href="<?php echo $url.'Social' ?>/edit/id/1?id=1" class="btn bg-primary-400 rounded-round btn-icon btn-sm"  ><i class="icon-facebook"></i><br/>Social Icons</a>
   	</div>
								</div>
								<!-- /available hours -->

							</div>



 




							<div class="col-sm-4"> 	<!-- Available hours -->
								<div class="card text-center">
									<div class="card-body">
 	<!-- Progress counter -->
 
<a style="width: 120px; height: 120px; padding: 20px; font-size: 15px;" href="<?php echo $url.'Pages/edit/id/4?id=4' ?>" class="btn bg-warning-400 rounded-round btn-icon btn-sm"><i class="icon-envelope"></i><br/>Contact Us</a>
   	</div>
								</div>
								<!-- /available hours -->

							</div>


						 

							 
					</div>
  
				</div>
				<!-- /dashboard content -->

	</div>	</div>