<h1>Report</h1>

   <table id="table1" class="gtable sortable">
       <thead>
        <tr>
            <th>level</th>
            <th>user`s In Level</th>
            <th>Success</th>
            <th>Fail</th>
        </tr></thead>
<?php foreach($this->reportData as $value): ?>
        <tr>
            <td><?php echo $value['level'] ?></td>
            <td><?php echo $value['urinlv'] ?></td>
            <td><?php echo $value['success'] ?></td>
            <td><?php echo $value['fail'] ?></td>

        </tr>

<?php endforeach; ?>
        
    </table>


<div class="clear"></div>