 <?php  foreach($this->Page as $value): ?>
 
 
 
     <!--breadcumb area start -->

   <!--Page Title-->
    <section class="page-title" style="background-image:url(<?php echo constant('APP_BASEURL').'/MyUpload/'.$value->Header ; ?>);">
        <div class="auto-container">
            <div class="inner-container clearfix">
                <h1><?php  echo $value->title ?></h1>
                <ul class="bread-crumb clearfix">
                    <li><a href="<?php echo LANG_URL ?>">Home</a></li>
                    <li></li>
                </ul>
            </div>
        </div>
    </section>
    <!--End Page Title-->

    
        
<div class="sidebar-page-container">
        <div class="auto-container">

            <div class="row ">
                <!--Content Side-->
                <div class="content-side col-lg-12 col-md-12 col-sm-12">
                    <div class="property-detail">
                        <div class="upper-box">
<div class="sec-title" style="width: 100%;">                 
                    <h2><?php echo $value->title2; ?></h2> </div>
                    <?php echo $value->Data; ?>
                      </div>
                  </div>
              </div>
            
            </div>
        </div>
    </div>

    <!--End Page Title-->







 





 

<section class="property-search-section" style="margin-top: 0px;">
        <div class="auto-container">
            <div class="property-search-tabs tabs-box">
                <ul class="tab-buttons">
                    <li data-tab="#sale" class="tab-btn  ">GET A FREE QUOTE </li>
                
                </ul>

                <div class="tabs-content">
                    <!--Tab / Active Tab-->
                    <div class="tab active-tab" id="sale">                         
                        <div class="property-search-form">
                     	<form method="post" action="" id="quoteform" name="quoteform" >
                                <div class="row">
                             
 <h5 class="view-messages" style="width: 100%;color: #df1b23; margin:20px 0;    padding: 0px;"><?php  echo $this->messageVi ?> </h4> 
		<input style="display:none"  name="created_on" id="created_on" value="<?php echo date("Y/m/d") ?>" />
                                    <!-- Form Group -->
                                    <div class="form-group col-lg-4 col-md-6 col-sm-12">
                                        <label>Name*</label>
                                        <input type="text" name="title" id="title" placeholder=" " required="">
                                    </div>

                                    <!-- Form Group -->
                                    <div class="form-group col-lg-4 col-md-6 col-sm-12">
                                        <label>Email*</label>
                                        <input type="email" name="email" id="email" placeholder=" " required="">
                                    </div>

                                    <!-- Form Group -->
                                    <div class="form-group col-lg-4 col-md-6 col-sm-12">
                                        <label>Services*</label>
                                        <select name="services" id="services"  class="select2-hidden-accessible" tabindex="-1" aria-hidden="true" required>
 <option value="">Plumbing Repair/Installation</option>
 <option value="Heating Repair/Installation">Heating Repair/Installation</option>
 <option value="Oil to Gas Conversions">Oil to Gas Conversions</option>
 <option value="Drains/Sewer Repair">Drains/Sewer Repair</option>
 <option value="Renovations">Renovations</option>
 <option value="Sump Pump">Sump Pump</option>
 <option value="Emergency Services">Emergency Services</option> </select><span class="select2 select2-container select2-container--bootstrap" dir="ltr" style="width: 426.979px;"><span class="selection"><span class="select2-selection select2-selection--single" role="combobox" aria-haspopup="true" aria-expanded="false" tabindex="0" aria-labelledby="select2-0g1t-container"><span class="select2-selection__rendered" id="select2-0g1t-container" title="Plumbing Repair/Installation">Plumbing Repair/Installation</span><span class="select2-selection__arrow" role="presentation"><b role="presentation"></b></span></span></span><span class="dropdown-wrapper" aria-hidden="true"></span></span>
                                       
                                    </div>

                                   

                                   
                                   
                                   <!-- Form Group -->
                                    <div class="form-group col-lg-10 col-md-6 col-sm-12">
                                        <input type="text" name="help" id="help" placeholder="How may we help you?" required="">
                                    </div>


                                    <!-- Form Group -->
                                    <div class="form-group col-lg-2 col-md-6 col-sm-12">
                                        <button type="submit" name="save2" id="save2" class="theme-btn btn-style-two">Submit Now...</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <!--Tab -->
                      
                    </div>
                </div>
            </div>
        </section>
  
 <?php endforeach ?>