<?php foreach($this->Page as $value) : ?> 
<?php $idid = $value->id; ?>
 
    <!--breadcumb area start -->
        <div class="breadcumb-area breadcumb-2 overlay pos-rltv" style="background-image:url(<?php echo constant('APP_BASEURL').'/MyUpload/'.$value->Header; ?>);    background-size: cover;">
            <div class="bread-main">
                <div class="bred-hading text-center">
                    <h5 class="" ><?php echo $value->titleAr; ?></h5> </div>
                <ol class="breadcrumb">
                    <li class="home"><a title="Go to Home Page" href="<?php echo LANG_URL ?>ar">الرئيسيه</a></li>
            
                </ol>
            </div>
        </div>
        <!--breadcumb area end -->
		
 <style>
 .about-des ul li {
      display: revert;
    margin-left: 20px;
    list-style: square;
	font-size: 16px;
 }
 </style>
 
 


<div class="about-us-area ptb-20">
            <div class="container">
                <div class="row">
                 <!--   <div class="col-lg-12 text-center">
                        <div class="heading-title heading-style pos-rltv mb-20 text-center">
                            <h5 class="uppercase"><?php echo $value->title; ?></h5>
                        </div>
                    </div> -->
                    <div class="about-us-wrap row">
                    
                        <div class="col-lg-12">
                            <div class="about-des">
   <div class="col-lg-12">
                                <p><?php echo $value->descriptionAr; ?></p></div>
                               
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>









<?php if( $value->type2 == 'article'): ?>

	
	<div class="shop-main-area pt-0 pb-40">
            <div class="container">
                <div class="row">	
		
		<div class="col-lg-12 col-md-12 order-lg-12 order-md-2">
                       <div class="row">
<h4 style="font-weight: bold; text-align: center; width: 100%; padding-bottom: 10px;" > جميع المقالات بقلم خالد أبو بكر</h4>
                           
 <?php  $model = new Model_PlusData();  $model->_name  = 'articles'; $articles = $model->selectForArray(array(  ), array( 'datepicker' => 'DESC')   );  foreach($articles as $article): ?>
 
                            <div class="col-lg-4" style="margin-bottom:60px;text-align:center;" >
                                <div class="single-blog sb-2 mb-30">
                                    <div class="blog-img pos-rltv product-overlay">
 <a href="<?php echo LANG_URL ?>ar/<?php echo (trim($article->pagurl)?'article/'.trim($article->pagurl):'article/v/i/'.$article->id) ?>"><img src="<?php echo constant('APP_BASEURL').'/MyUpload/'.$article->thumb; ?>" ></a>
                                    </div>
                                    <div class="blog-content">
                                        <div style="    padding: 20px 10px 20px 10px;">
                                            <h5 class="uppercase font-bold"><?php echo $article->titleAr; ?></h5>
                                            <div class="like-comments-date">
 <a href="<?php echo LANG_URL ?>ar/<?php echo (trim($article->pagurl)?'article/'.trim($article->pagurl):'article/v/i/'.$article->id) ?>" class="btn-def small" tabindex="0">المزيد</a>
                                            </div>
                                           
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <?php endforeach; ?>
                            
                            
                     
                        </div>
                    </div>
     </div>    </div>    </div>
 
 <?php endif; ?>   









<?php if( $value->type2 == 'news'): ?>

	
	<div class="shop-main-area pt-0 pb-40">
            <div class="container">
                <div class="row">	
		
		<div class="col-lg-12 col-md-12 order-lg-12 order-md-2">
                       <div class="row">
                           
 <?php  $model = new Model_PlusData();  $model->_name  = 'news'; $articles = $model->selectForArray(array(  ), array( 'datepicker' => 'DESC')   );  foreach($articles as $article): ?>
 
                            <div class="col-lg-4" style="margin-bottom:60px;text-align:center;" >
                                <div class="single-blog sb-2 mb-30">
                                    <div class="blog-img pos-rltv product-overlay">
 <a href="<?php echo LANG_URL ?>ar/<?php echo (trim($article->pagurl)?'news/'.trim($article->pagurl):'article/v/i/'.$news->id) ?>"><img src="<?php echo constant('APP_BASEURL').'/MyUpload/'.$article->thumb; ?>" ></a>
                                    </div>
                                    <div class="blog-content">
                                        <div style="    padding: 20px 10px 20px 10px;">
                                            <h5 class="uppercase font-bold"><?php echo $article->titleAr; ?></h5>
                                            <div class="like-comments-date">
 <a href="<?php echo LANG_URL ?>ar/<?php echo (trim($article->pagurl)?'news/'.trim($article->pagurl):'article/v/i/'.$news->id) ?>" class="btn-def small" tabindex="0">المزيد</a>
                                            </div>
                                           
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <?php endforeach; ?>
                            
                            
                     
                        </div>
                    </div>
     </div>    </div>    </div>
 
 <?php endif; ?>   



<?php if( $value->type2 == 'Contact'): ?>
												 <?php  $model = new Model_PlusData();
   $model->_name  = 'Pages'; $toppages = $model->selectForArray(array( 'type2' => 'Contact' ), array( ) , 1  ); 
 foreach($toppages as $contact): ?>  <?php endforeach; ?>
<!--contact info are start-->
        <div class="contact-info ptb-40">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                         <div class="row">
                             <div class="col-lg-12">
  <form id="contact-form" class="row framm" action="" method="post"   style=" width: 100%;" >
                 
                                <!-- Field 1 -->
       <?php  ($this->messageVi)  ?>
                <?php echo '<p style="width: 100%;color: red;">' . $this->messageVi . '</p>' ?>
                                     <div class="col-md-6">
                                         <div class="input-box mb-20">
                      <input required  name="name" class="info" placeholder="Name*" type="text">
                                         </div>
                                     </div>
                                     <div class="col-md-6">
                                         <div class="input-box mb-20">
                                             <input name="email" class="info" placeholder="Email*" type="email">
                                         </div>
                                     </div>
                                     <div class="col-md-6">
                                         <div class="input-box mb-20">
                                             <input name="phone" class="info" placeholder="Phone*" type="text">
                                         </div>
                                     </div>
                                     <div class="col-md-6">
                                         <div class="input-box mb-20">
                                             <input name="country" class="info" placeholder="Country*" type="text">
                                         </div>
                                     </div>
                                     <div class="col-md-12">
                                         <div class="input-box mb-20">
                                             <textarea name="message" class="area-tex" placeholder="Your Message*"></textarea>
                                         </div>
                                     </div>
                                      <p class="form-messege"></p>
                                     <div class="col-xs-12">
                                         <div class="input-box"  style="margin-left:20px;">
           <input style="cursor: pointer;width: 100%;margin-right: 22px;background: #000;color: #fff;" name="save7" id="save7"  class="sbumit-btn" value="Send" type="submit">
                                         </div>
                                     </div>
                                 
                                 </form>
                             </div>
                         </div>
                    </div>
                    <div class="col-md-6">
                        <div class="single-footer contact-us contact-us-2">
                            <!--  <div class="heading-title text-center mb-10">
                               <h5 class="uppercase">Contact Info</h5>  
                                </div> -->
                            <ul class="contact-info"> 
							    <li style="margin-bottom: 0px;">
                                    <div class="contact-icon"> <i class="zmdi zmdi-pin-drop"></i> </div>
                                        <p><?php echo $contact->addressar; ?></p>
                                    </div>
                                </li>
								
								 
					 
								
                            <?php if(trim($contact->mainphone)): ?>     <li>
                                    <div class="contact-icon"> <i class="zmdi zmdi-phone-paused"></i> </div>
                                    <div style="margin-left:52px;" >
                                        <a style="color:#000;" ><?php echo $contact->mainphone; ?> </a>
                                    </div>
                                </li><?php endif; ?>
								 
								
						<?php if(trim($contact->fax)): ?>  <li  >
                                    <div class="contact-icon"> <i class="fa fa-fax"></i> </div>
                                    <div style="margin-left: 47px;min-height: 50px; " >
                                        <p style="color:#000;"  ><?php echo $contact->fax; ?></p>
                                    </div>
                                </li>  <?php endif; ?>
								
								
                                <li style="margin-top: 10px;" >
                                    <div class="contact-icon"> <i class="zmdi zmdi-email-open"></i> </div>
                                    <div style="margin-left: 52px;" >
                                        <p><a style="color:#000;"  href=mailto://<?php echo $contact->email; ?>"><?php echo $contact->email?></a>										 </p>
                                    </div>
                                </li>
                              
                            </ul>
                        
                        </div>
                    </div>
                    <div class="col-lg-12">
                       <div class="pos-rltv">
                            <div class="contact-des">
							<iframe src="https://www.google.com/maps/embed?<?php echo $contact->mapGoogle; ?>" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
                               
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--contact info are end-->
		 
 
<?php endif; ?>









 







<?php if( $value->type2 == 'videos'): ?>
 
 
        <div class="choose-us-area pb-0" style="margin-top: 0px;  padding-top: 10px;  margin-bottom: 40px;  color: #fff;">
            <div class="container">
                <div class="row">
                                     
 <?php  $model = new Model_PlusData();  $model->_name  = 'videos'; $videos = $model->selectForArray(array(  ), array( 'displayorder' => 'ASC')   );  foreach($videos as $video): ?>
                    <div class="col-lg-4 col-md-4">
                        <div class=" ">
                            <div class="choose-i">
                             <iframe width="100%"  class="videoo" src="https://www.youtube.com/embed/<?php echo $video->video ; ?>" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
							 <h5> sss</h5>
                            </div>
                         </div>
                    </div>
					   <?php endforeach; ?>
                    
                       

                    
                </div>
            </div>
        </div>


                           
                         
                            
                            
                    
<?php endif; ?>


 
 
  
<?php if( $value->type2 == 'clients'): ?>


<section class="about-us style-two" style="padding: 0px;">
        <div class="auto-container">
            <div class="row">
                
		  <?php $model = new Model_PlusData();    $model->_name  = 'Clients';    $hoem = $model->selectForArray(array(), array( 'displayorder' => 'ASC' )  );
								foreach($hoem as $client):	?> 
				<div class="video-column col-xl-3 col-lg-7 col-md-12 col-sm-12">
                    <div class="inner-column">
                        <div class="video-box">
                            <figure class="image">
 <a href="<?php echo $client->photo; ?>" > <img src="<?php echo constant('APP_BASEURL').'/MyUpload/'.$client->photo; ?>" > </a></figure>
                             
                        </div>
                    </div>
                </div>
              <?php endforeach; ?>
            </div>
        </div>
    </section>


 <?php endif; ?>

  
<?php if( $value->type2 == 'services'): ?>

<?php $model = new Model_PlusData();    $model->_name  = 'servicescategories';    $hoem = $model->selectForArray(array(), array( )  );
								foreach($hoem as $services):	?> 


<section class="about-us style-two" style="padding: 0px;">
        <div class="auto-container">
            <div class="row">
                
				 <div class="info-column col-xl-6 col-lg-12 col-md-12 col-sm-12">
                    <div class="inner-column">
                        <div class="sec-title">
                    
                            <h2><?php echo $services->title; ?></h2>
                        </div>

                        <div class="text"><?php echo $services->Data; ?> </div>

                        
                    </div>
                </div>
				
				
				<div class="video-column col-xl-6 col-lg-7 col-md-12 col-sm-12">
                    <div class="inner-column">
                        <div class="video-box">
                            <figure class="image"><img src="<?php echo constant('APP_BASEURL').'/MyUpload/'.$services->Thumb; ?>" ></figure>
                             
                        </div>
                    </div>
                </div>
             
            </div>
        </div>
    </section>

 <?php endforeach; ?>



 <?php endif; ?>
 
 
 
 
 
 
 
   
<?php if( $value->type2 == 'gallery'): ?>

<div class="choose-us-area pb-70">
            <div class="container">
                <div class="row">
                     
 <?php $model = new Model_PlusData();    $model->_name  = 'gallery';    $photos = $model->selectForArray(array(), array( 'displayorder' => 'ASC' )  );
								foreach($photos as $photo):	?> 
                          <div class="col-lg-4 col-md-4" style="margin-bottom:30px;" >
                        <div class=" ">
                            <div class="choose-icon pos-rltv">
 <a  style="z-index: 999999999;" class="fancybox" data-fancybox-group="group" href="<?php echo constant('APP_BASEURL').'/MyUpload/'.$photo->Thumb; ?>">
         <img style="width: 100%;" src="<?php echo constant('APP_BASEURL').'/MyUpload/'.$photo->Thumb; ?>"  /></a>
                        </div>
                                <h5 style="margin-top: 20px;" ><b> </b> </h5>
                           
                         </div>
                    </div>

                    <?php endforeach; ?>
                </div>
            </div>
        </div>
		
     

					<?php endif; ?>
					
 
 <?php if( $value->type2 == 'certificates'): ?>

								
 <div class="about-us-area ptb-0" style="margin-bottom:30px;" >
            <div class="container">  <div class="row">
			 
 <?php $model = new Model_PlusData();    $model->_name  = 'certificates';    $certificates = $model->selectForArray(array(), array('displayorder' => 'ASC')  );
								foreach($certificates as $index =>$certificate):	?>
								 
			 <div class="col-lg-4 text-center" style="margin-bottom: 70px;" >
                        <div class="heading-title heading-style pos-rltv mb-50 text-center">
                            <h5 class="uppercase"><?php echo $certificate->Name; ?></h5>
                        </div>
                   
                          <div class="col-lg-12">
                            <div class="about-img"><img src="<?php echo constant('APP_BASEURL').'/MyUpload/'.$certificate->thumb ; ?>" ></div>
							<p><?php echo $certificate->Details; ?></p>
                               
                        </div> </div>
                  	<?php endforeach; ?>    
                    
                </div>
            </div>
        </div>
	
  	<?php endif; ?>
	
	
	
	
	
	
	 <?php if( $value->type2 == 'partners'): ?>

								
 <div class="about-us-area ptb-0" style="margin-bottom:30px;" >
            <div class="container">  <div class="row">
			 
 <?php $model = new Model_PlusData();    $model->_name  = 'partners';    $partners = $model->selectForArray(array(), array('displayorder' => 'ASC')  );
								foreach($partners as $index =>$partner):	?>
								 
			 <div class="col-lg-3 text-center" style="margin-bottom: 70px;" >
                        <div class="heading-title heading-style pos-rltv mb-50 text-center">
                            <h5 class="uppercase"><?php echo $partner->title; ?></h5>
                        </div>
                   
                          <div class="col-lg-12">
                            <div class="choose-icon pos-rltv"><img style="width: 100%;" src="<?php echo constant('APP_BASEURL').'/MyUpload/'.$partner->logo ; ?>" ></div>
							<p><?php echo $partner->data; ?></p>
                               
                        </div> </div>
                  	<?php endforeach; ?>    
                    
                </div>
            </div>
        </div>
	
  	<?php endif; ?>
					
 
 
 
					
<!-- Sections -->
<?php $model = new Model_PlusData();    $model->_name  = 'PageSections';     $where = array('pageid' => ($value->id));
						        $toppages = $model->selectForArray($where, array('id' => 'ASC')  );
								foreach($toppages as $index =>$PageSections):	?>

 <?php if($PageSections->style == '1'): ?> 
  <div class="about-us-area ptb-0">
            <div class="container">  <div class="row">  
 <?php if($value->id != '1'):?>  <div class="col-lg-12 text-center">
                      <div class="heading-title heading-style pos-rltv mb-50 text-center">
                            <h5 class="c"><?php echo $PageSections->titleAr; ?></h5>
                        </div> 
                    </div>  <?php endif; ?> 
                        <div class="col-lg-6">
                            <div class="about-img"><img  style="padding-bottom:20px;" src="<?php echo constant('APP_BASEURL').'/MyUpload/'.$PageSections->Thumb ; ?>" ></div>
                        </div>
                        <div class="col-lg-6">
                            <div class="about-des">
                               <?php echo $PageSections->descriptionAr; ?>
                               
                            </div>
                      
                    </div>
                </div>
            </div>
        </div>
				
   
 <div class="col-md-12" style="margin-bottom:30px;" ></div>


<?php elseif($PageSections->style == '2'): ?> 
   <div class="about-us-area ptb-0">
            <div class="container">  <div class="row"> 
 <?php if($value->id != '1'):?>  <div class="col-lg-12 text-center">
                        <div class="heading-title heading-style pos-rltv mb-20 text-center">
                            <h5 class="uppercase"><?php echo $PageSections->titleAr; ?></h5>
                        </div>
                    </div> <?php endif; ?>
              
                        <div class="col-lg-12">
                            
                           <?php echo $PageSections->descriptionAr; ?>
                         
                        </div>
                 
                </div>
            </div>
        </div>
 
  
 <div class="col-md-12" style="margin-bottom:30px;" > </div>


<?php elseif($PageSections->style == '3'): ?>

   <div class="about-us-area ptb-0">
            <div class="container">  <div class="row">  
 <div class="col-lg-12 text-center">
                        <div class="heading-title heading-style pos-rltv mb-50 text-center">
                            <h5 class="uppercase"><?php echo $PageSections->titleAr; ?></h5>
                        </div>
                    </div> 
              
                        <div class="col-lg-6">
                            <div class="about-des">
                              <?php echo $PageSections->descriptionAr; ?>
                            </div>
                        </div>
						   <div class="col-lg-6">
                            <div class="about-img"><img src="<?php echo constant('APP_BASEURL').'/MyUpload/'.$PageSections->Thumb ; ?>" ></div>
                        </div>
                   
                </div>
            </div>
        </div>

 <div class="col-md-12" style="margin-bottom:30px;" > </div>
 
<?php endif; ?>

<?php endforeach; ?>


</div></div> 

<!-- Sections -->
 
 
<!-- Sections -->

 
                
            </div>
        </div>
    </section>
	
	
	
<?php endforeach; ?>

  