  <link rel="stylesheet" href="<?=$this->baseUrl()?>/resources/css/jquery.Jcrop.min.css" type="text/css" />
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-7s5uDGW3AHqw6xtJmNNtr+OBRJUlgkNJEo78P4b0yRw= sha512-nNo+yCHEyn0smMxSswnf/OnX6/KwJuZTlNZBjauKhTK0c+zT+q5JOCx0UFhXQ6rJR9jg6Es8gPuD2uZcYDLqSw==" crossorigin="anonymous">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha256-KXn5puMvxCw+dAYznun+drMdG1IFl3agK0p/pqT9KAo= sha512-2e8qq0ETcfWRI4HJBzQiA3UoyFk6tbNyG+qSaIBZLyW9Xf3sWZHN/lxe9fTh1U45DpPf07yj94KsUHHWe4Yk1A==" crossorigin="anonymous"></script>
  <script type="text/javascript" src="<?= $this->baseUrl(); ?>/ui/editor/tinymce/tiny_mce.js"></script>

  <script type="text/javascript">


	$(document).ready(function() {
        $('#image, #image2').on('change', function(){
            var p = $("#preview");
            var oFReader = new FileReader();
            oFReader.readAsDataURL(document.getElementById($(this).attr('id')).files[0]);
            oFReader.onload = function (oFREvent) {
                p.attr('src', oFREvent.target.result).fadeIn();
            };
            $('#preview').Jcrop();
            $('#myModal').modal();
        });
        $('#save-label label').hide();
	 });
</script>
<script type="text/javascript">
    tinyMCE.init({
            // General options
            //mode : "textareas",
            mode : "exact",
            elements : "elm1,elm2,elm3,elm4,elm5",
            language : "en",
            theme : "advanced",
            plugins : "imagemanager,filemanager,safari,pagebreak,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",
            // Theme options
            theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,formatselect,fontselect,fontsizeselect",
            theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
            theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
            /*theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak",*/
            theme_advanced_toolbar_location : "top",
            theme_advanced_toolbar_align : "left",
            //theme_advanced_statusbar_location : "bottom",
            theme_advanced_resizing : true,
            // Example content CSS (should be your site CSS)
            content_css : "jscripts/css/content.css",
            // Drop lists for link/image/media/template dialogs
            template_external_list_url : "lists/template_list.js",
            external_link_list_url : "lists/link_list.js",
            external_image_list_url : "lists/image_list.js",
            media_external_list_url : "lists/media_list.js",
            // Replace values for the template plugin
            template_replace_values : {
				username : "Some User",
				staffid : "991234"
            }
    });


</script>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
            <img id="preview" height="300" width="575">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

<style>
    .tinymce body, td, pre
    {
        direction: rtl !important ;
    }

</style>


<h1> <?php echo $this->typename ?></h1>
<?php echo $this->form ?>



<?php if($this->typename == 'Services  Image' ): ?>

<script type="text/javascript" src="<?php echo $this->themeUrl ?>js/jquery.ajup.js"></script>
 <script src="http://code.jquery.com/jquery-1.10.2.js"></script>
  <script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>



<script>
$(document).ready(function (){
    $("input.xxxx").click(function(){
      var con = []


$('#sortable img' ).each(function myFunction (index, value){

var src = $(this).attr('src');
var tarr = src.split('/');
var file = tarr[tarr.length-1];
var data = file.split('.')[0];


con.push(file);


  });




var txt = "";
var x;
for (x in con) {
    txt += con[x] + "||";
}
      $("#content").val('||'+ txt);
    });
});


</script>



<script type="text/javascript">
<!--

var imgs = new Array();

function showimgs(){
    if(imgs.length<=0){
        $('.imageuploader .files').html("<div style=\"font-size: small;\">No image uploaded</div>");
        $('.image').val('');
    }else{
        $('.imageuploader .files').html("<table ><tr><td >   ");
        $('.image').val("");
        for (var i = 0; i < imgs.length; i++) {
            // add file to the list
            $('.imageuploader .files').html($('.imageuploader .files').html()+"<div > <a id="+i+" href='javascript:removeimg("+i+");'><br />Remove</a><br /> <img    id="+i+" src='<?php echo $this->baseUrl() ?>/files/ful/i/"+imgs[i]+"'     width='50' height='50'></img> <br/>     </div>");
            $('.image').val($('.image').val()+'||'+imgs[i]);
        }
    }
}



  $(function  () {
  $( "#sortable" ).sortable();
         });

function removeimg(id){
    imgs.splice(id,1);
  showimgs();
$('#sortable img' ).each(function myFunction (index, value){

var src = $(this).attr('src');
var tarr = src.split('/');
var file = tarr[tarr.length-1];
var data = file.split('.')[0];


con.push(file);


  });
var txt = "";
var x;
for (x in con) {
    txt += con[x] + "||";
}
      $("#content").val('||'+ txt);




}

	(function($){

            var button1 = '<div class="imageuploader"><div class=" "><div id="button1" class="btn btn-danger" ><button class="btn btn-danger"> Add Photo</button></div></div> <br/><input type="button" value="Save Left Gallery Order" class="xxxx"></input><input id="content" type="hidden" class="image" style="width: 250px;" name="table_image" value="<?php echo $this->form->getElement('table_image')->getValue(); ?>" /><div class="files" style="cursor:pointer"  id="sortable" >11</div>  </div>';
	    $('#table_image').replaceWith(button1);
		if($('#button1').length){
	        var button = $('#button1'), interval;
	        new AjaxUpload(button, {
	            action: '<?php echo $this->baseUrl().'/admin/upload/photo'?>',
	            name: 'img',
	            onSubmit : function(file, ext){
	                if (ext && /^(jpg|jpeg|gif|png)$/i.test(ext)){
	                    // change button text, when user selects file
	                button.text('upload process');

	                // If you want to allow uploading only 1 file at time,
	                // you can disable upload button
	                this.disable();

	                // Uploding -> Uploading. -> Uploading...
	                interval = window.setInterval(function(){
	                    var text = button.text();
	                    if (text.length < 13){
	                        button.text(text + '.');
	                    } else {
	                        button.text('upload till process.........');
	                    }
	                }, 200);

	                } else {
	                    // cancel upload
	                    alert("  gif,jpg,jpeg,png extention allow");
	                    return false;
	                }
	            },
	            onComplete: function(file, response){
	                button.text('Upload new image');

	                window.clearInterval(interval);

	                // enable upload button
	                this.enable();

	                imgs.push( response );
	                showimgs();
	            }
	        });
	        if($('.image').val()!=''){
	            imgs=$('.image').val().split('||');

	            for (var i = 0; i < imgs.length; i++) {
	                if(imgs[i]==''){
	                    imgs.splice(i,1);
	                    i=i-1;
	                }
	            }
	        }
	        showimgs();
$('#sortable img' ).each(function myFunction (index, value){

var src = $(this).attr('src');
var tarr = src.split('/');
var file = tarr[tarr.length-1];
var data = file.split('.')[0];


con.push(file);


  });
var txt = "";
var x;
for (x in con) {
    txt += con[x] + "||";
}
      $("#content").val('||'+ txt);


	    }



	})(jQuery);
//-->

</script>










</script>





<?php endif ?>
























<?php if($this->typename == 'Project Category' ): ?>

  <script src="https://code.jquery.com/jquery-1.10.2.js"></script>

 <script>
$( '#pageid' ).attr( 'onchange' , 'myFunction()'  );
$( '#data5' ).attr( 'type' , 'hidden'  );
</script>


<script type="text/javascript">

function myFunction() {

    var pageidx = document.getElementById("pageid");
    document.getElementById("data5").value = pageidx.options[pageidx.selectedIndex].text;
}
</script>

  <script type="text/javascript" src="<?=$this->baseUrl()?>/resources/scripts/jquery.Jcrop.js"></script>



<?php endif ?>