 
<?php  $currentdate2 = date("Y-m-d") ; $packagesid = array() ; 
                        $modelCities = new Model_PlusData();
                        $modelCities->_name = 'popup'; 
                        $where = array();
                        $toppages = $modelCities->selectForArray(array( 'show_home' => '1' , 'id' =>  '2'  ), array('displayorder' => 'DESC')  );
                        foreach ($toppages as $values):
                        ?>
 
<?php if(($values->expiredate == '') || ($values->expiredate > $currentdate2) ): ?>
 
 <div id="thover"></div>  <div id="tpopup"><h3> <?php echo $values->title; ?> </h3>
 <div style="padding: 20px;"> <?php echo $values->data; ?>  </div><div id="tclose">X</div> </div>
 
 <?php endif; ?> 

<?php  endforeach; ?>
  
  <!-- Banner Section -->
     <div class="slider-area pos-rltv carosule-pagi cp-line">
            <div class="active-slider">
            <!-- Slide Item -->
                        
  <?php $model = new Model_PlusData();    $model->_name  = 'home-slider'; 
  $toppages = $model->selectForArray(array( ), array('displayorder' => 'ASC')   );  ?>
<?php foreach($toppages as $index =>$HomeSlider):?>



<div class="single-slider pos-rltv">
                    <div class="slider-img"><img style="width: 100%;"  src="<?php echo constant('APP_BASEURL').'/MyUpload/'.$HomeSlider->Header; ?>" ></div>
                    <div class="slider-content pos-abs">
                          <h4></h4>
                    <?php if(trim($HomeSlider->daraAr)): ?> <h2 class="uppercase pos-rltv underline"><?php echo $HomeSlider->daraAr; ?> </h2> <?php endif; ?>
                    </div>
                </div>

          <?php endforeach; ?>
          
        </div>
</div>
    <!--End Banner Section -->
    
	
	
	
	
	
	
	

<?php $model = new Model_PlusData();    $model->_name  = 'home-page-section';     $where = array('id' => '1'  );
						        $hoem = $model->selectForArray(array(), array( )  );
								foreach($hoem as $homepage):	?> 
								
								
<div class="about-us-area ptb-70">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <div class="heading-title heading-style pos-rltv mb-50 text-center">
                            <h3 class="uppercase"><?php echo $homepage->titleAr; ?>  </h5>
                        </div>
                    </div>
                    <div class="about-us-wrap row">
                        <div class="col-lg-6">
                            <div class="about-img"><img  style="width:100%;" src="<?php echo constant('APP_BASEURL').'/MyUpload/'.$homepage->Photo1; ?>" ></div>
                        </div>
                        <div class="col-lg-6">
                            <div class="about-des">
                                <p><?php echo $homepage->TextUnderSliderAr; ?></p>
                                <a href="<?php echo $homepage->Link; ?>" class="btn-def small" tabindex="0">المزيد</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    

 <?php endforeach; ?>
 
 
 
  
        <div class="choose-us-area pb-70" style="color: #fff;background: #000;;padding-top: 40px;">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <div class="heading-title heading-style pos-rltv mb-50 text-center">
                            <h3 class="uppercase"> الميديــا </h3>
                        </div>
                    </div>
					
					  

 <?php  $model = new Model_PlusData();   $model->_name  = 'Pages'; $toppages = $model->selectForArray(array( 'type2' => 'article' ), array( ) , 1  ); 
 foreach($toppages as $page): ?> 
 <div class="col-lg-4 col-md-4">
                        <div class=" ">
                            <div class="choose-icon pos-rltv">
 <a href="<?php echo LANG_URL ?>ar/<?php echo (trim($page->pagurl)?''.trim($page->pagurl):'page/v/i/'.$page->id) ?>">   <img src="<?php echo THEME_DIR ?>images/articel.jpg" style="width: 100%; padding: 10px; border: 1px solid white; margin-bottom: 20px;"> 
                                <h5 style="text-align: center;"><b><?php echo $page->titleAr; ?> </b> </h5> </a>
                            </div>
                         </div>
                    </div>
<?php endforeach; ?>

 
  <?php  $model = new Model_PlusData();   $model->_name  = 'Pages'; $toppages = $model->selectForArray(array( 'type2' => 'videos' ), array( ) , 1  ); 
 foreach($toppages as $page): ?>
 <div class="col-lg-4 col-md-4">
                        <div class=" ">
                            <div class="choose-icon pos-rltv">
 <a href="<?php echo LANG_URL ?>ar/<?php echo (trim($page->pagurl)?''.trim($page->pagurl):'page/v/i/'.$page->id) ?>">   <img src="<?php echo THEME_DIR ?>images/video.jpg" style="width: 100%; padding: 10px; border: 1px solid white; margin-bottom: 20px;"> 
                                <h5 style="text-align: center;"><b><?php echo $page->titleAr; ?> </b> </h5> </a>
                            </div>
                         </div>
                    </div>
<?php endforeach; ?>
 
  <?php  $model = new Model_PlusData();   $model->_name  = 'Pages'; $toppages = $model->selectForArray(array( 'type2' => 'gallery' ), array( ) , 1  ); 
 foreach($toppages as $page): ?> 

 <div class="col-lg-4 col-md-4">
                        <div class=" ">
                            <div class="choose-icon pos-rltv">
 <a href="<?php echo LANG_URL ?>ar/<?php echo (trim($page->pagurl)?''.trim($page->pagurl):'page/v/i/'.$page->id) ?>">   <img src="<?php echo THEME_DIR ?>images/gallery.jpg" style="width: 100%; padding: 10px; border: 1px solid white; margin-bottom: 20px;"> 
                                <h5 style="text-align: center;"><b><?php echo $page->titleAr; ?> </b> </h5> </a>
                            </div>
                         </div>
                    </div>
                    
 <?php endforeach; ?>                               
                                            

                    
                    
                </div>
            </div>
        </div>
        
        
        
          
            
                    
                </div>
            </div>
        </div>
		
 
 
 
    <!--branding-section-area start-->
        <div class="branding-section-area" style="background: rgba(0, 0, 0, 0) url(<?php echo THEME_DIR ?>images/bg/brand-bg.jpg) no-repeat scroll center center / cover;">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="active-slider pos-rltv carosule-pagi cp-line pagi-02">
                            <div class="single-slider">
                                <div class="row">
                                    <div class="col-xl-6 col-lg-6 col-md-6">
                                        <div class="brand-img text-center">
                                           
 <?php  $model = new Model_PlusData();   $model->_name  = 'Pages'; $toppages = $model->selectForArray(array( 'type2' => 'about' ), array( ) , 1  ); 
 foreach($toppages as $page): ?>   <?php endforeach; ?> 
                                        </div>
                                    </div>
                                    <div class="col-xl-6 col-lg-6 col-md-6">
                                        <div class="brand-content ptb-55">
                                            <div class="brand-text color-lightgrey">
                                                <h3 style="text-align: right;" > مكتب الاستاذ ابو بكر للمحاماه  </h6>
                                                
                                               <?php  echo $homepage->MissionAr;  ?>
 <?php  $model = new Model_PlusData();   $model->_name  = 'Pages'; $toppages = $model->selectForArray(array( 'type2' => 'profile' ), array( ) , 1  ); 
 foreach($toppages as $page): ?>  
  <a style="color:#fff;margin-bottom:10px;float:right;" href="<?php echo LANG_URL ?>ar/<?php echo (trim($page->pagurl)?''.trim($page->pagurl):'page/v/i/'.$page->id) ?>" class="btn-def small" tabindex="0">المزيد</a>
                                                <div class="social-icon-wraper mt-35" style="margin-top: 65px;" >
                                                    
 <?php endforeach; ?> 
                                                      
                                                </div>
                                            </div>
                                          
                                        </div>
                                    </div>
                                </div>
                            </div>
                           
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--branding-section-area end-->

       
	   
	   
	   
   
       <!-- <div class="choose-us-area pb-0" style="margin-top: 60px;  padding-top: 90px; background: black;  margin-bottom: 40px;  color: #fff;">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <div class="heading-title heading-style pos-rltv mb-50 text-center">
                            <h3 class="uppercase">Latest Media  </h3>
                        </div>
                    </div>
 <?php  $model = new Model_PlusData();  $model->_name  = 'videos'; $videos = $model->selectForArray(array(  ), array( 'displayorder' => 'ASC')  , 3 );  foreach($videos as $video): ?>					 
                    <div class="col-lg-4 col-md-4">
                        <div class=" ">
                            <div class="choose-i">
                             <iframe width="100%"  class="videoo" src="https://www.youtube.com/embed/<?php echo $video->video ; ?>"  frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                            </div>
                         </div>
                    </div>
                    
                      <?php endforeach; ?>
					  

                    
                </div>
            </div>
        </div> -->
		
		
		

        <!--banner area end-->
		 <?php  $model = new Model_PlusData();
   $model->_name  = 'Pages'; $toppages = $model->selectForArray(array( 'type2' => 'Contact' ), array( ) , 1  ); 
 foreach($toppages as $contact): ?>  <?php endforeach; ?>

        <div class="contact-info ptb-70" style="padding-bottom:0px; ">
            <div class="container" style="position: relative;">
                <div class="row">
                <div class="col-lg-12 text-center">
                        <div class="heading-title heading-style pos-rltv mb-50 text-center">
                            <h3 class="uppercase">  الاتصال بنا</h3>
                        </div>
                    </div>
                    
         
	 
				<div  class="col-md-6 " >
					<iframe src="https://www.google.com/maps/embed?<?php echo $contact->mapGoogle ; ?>" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
				</div>
				<div class="col-md-6 infobox-in-map"  >
					<div class="infobox-in-map-inner">
				 <form id="contact-form" class="row framm" action="" method="post"   style=" width: 100%;" >
                               
      <div class="col-md-12">
       <?php  ($this->messageVi)  ?>
                <?php echo '<p style="color:red;" >' . $this->messageVi . '</p>' ?>
                                         <div class="input-box mb-20">
                                             <input name="name" class="info" placeholder="Name*" type="text">
                                         </div>
                                     </div>
                                     <div class="col-md-12">
                                         <div class="input-box mb-20">
                                             <input name="email" class="info" placeholder=" Phone*" type="email">
                                         </div>
                                     </div>
                                     <div class="col-md-12">
                                         <div class="input-box mb-20">
                                             <input name="phone" class="info" placeholder=" Email*" type="text">
                                         </div>
                                     </div>
  <div class="col-md-12">
                                         <div class="input-box mb-20">
                                             <input name="country" class="info" placeholder=" Country*" type="text">
                                         </div>
                                     </div>
  <div class="col-md-12">
                                         <div class="input-box mb-20">
    <textarea  style="height: 150px;line-height: 20px;color:#626262;" name="message" class="info" placeholder="Your Message" type="text">Message </textarea>
                                         </div>
                                     </div>
                                   
                              
                                     <p class="form-messege"></p>
                                     <div class="col-xs-12">
                                         <div class="input-box"  style="margin-left:20px;">
           <input style="cursor: pointer;width: 100%;margin-right: 22px;background: #000;color: #fff;" name="save7" id="save7"  class="sbumit-btn" value="ارسال" type="submit">
                                         </div>
                                     </div>
                                 
                                 </form>
                        
 

				
						</span></a>
					</div>
				</div>
		 
         
     <div class="col-lg-12 text-center" style="margin-top:20px;">
                       
                    </div>


                    <div class="col-md-12">
                      
                         <div class="row">
                             <div class="col-lg-12" > 
                                 
                             </div>
                         </div>
                    </div>
                    
                </div>
            </div>
        </div>
 
 
 
 
 
 
  <!--new arrival area start-->
       <!--  <div class="new-arrival-area pt-70">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <div class="heading-title heading-style pos-rltv mb-50 text-center">
                           <h3 class="uppercase">Certifications</h3>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="row">
                    <div class="col-lg-12 total-new-arrival new-arrival-slider-active carsoule-btn">
                       
							 <?php  $model = new Model_PlusData();  $model->_name  = 'certificates'; $certificates = $model->selectForArray(array(  ), array( 'displayorder' => 'ASC')  );  foreach($certificates as $certificate): ?>
							 
              <div class="choose-icon pos-rltv">
 <a  style="z-index: 999999999;" class="fancybox" data-fancybox-group="group" href="<?php echo constant('APP_BASEURL').'/MyUpload/'.$certificate->thumb; ?>">
         <img style="width: 95%;padding: 20px;
    border: 1px solid #d7d7d7;height: 330px;" src="<?php echo constant('APP_BASEURL').'/MyUpload/'.$certificate->thumb; ?>"  /></a>
                        </div>
                          <?php endforeach; ?>
                       
                    </div>
                </div>
            </div>
        </div> -->
        <!--new arrival area end-->
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		<!-- QUICKVIEW PRODUCT -->
        <div id="quickview-wrapper">
            <!-- Modal -->
			
							 <?php  $model = new Model_PlusData();  $model->_name  = 'certificates'; $certificates = $model->selectForArray(array(  ), array( 'displayorder' => 'ASC')  );  foreach($certificates as $certificate): ?>
            <div class="modal modal<?php echo $certificate->id; ?> fade" id="productModal" tabindex="-1" role="dialog">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                    aria-hidden="true">&times;</span></button>
                        </div>
                        <div class="modal-body">
                            <div class="modal-product0">
                                <div class="product-images0">
                                    <!--modal tab start-->
                                    <div class="portfolio-thumbnil-area-20">
                                        <div class="tab-content active-portfolio-area-20">
                                            <div role="tabpanel" class="tab-pane active" id="view1">
                                                <div class="product-img">
 
<a  style="z-index: 999999999;" class="fancybox" data-fancybox-group="group" href="<?php echo constant('APP_BASEURL').'/MyUpload/'.$certificate->thumb; ?>">
         <img style="width: 100%;" src="<?php echo constant('APP_BASEURL').'/MyUpload/'.$certificate->thumb; ?>"  /></a>
 
 
  
                                                </div>
                                            </div>
                                              
                                        </div>
                                     
                                    </div>
                                </div>
                                <!--modal tab end-->
                                <!-- .product-images -->
                                <!-- <div class="product-info">
                                    
                                    <div class="price-box-3">
                                        <div class="s-price-box"> <h1> <?php echo $certificate->Name; ?></h1>   </div>
                                    </div>  
                                   
                                    <div class="quick-desc"> <?php echo $certificate->Details; ?></div>
                                    <div class="social-sharing-modal">
                                       
                                    </div>
                                </div> -> s
                                <!-- .product-info -->
                            </div>
                            <!-- .modal-product -->
                        </div>
                        <!-- .modal-body -->
                    </div>
                    <!-- .modal-content -->
                </div>
                <!-- .modal-dialog -->
            </div>
            <!-- END Modal -->
			<?php endforeach; ?>
        </div>
        <!-- END QUICKVIEW PRODUCT -->
 
