<?php 
$disc = null;
$discID = null;
$finalvar = null;
$discDATE = null;
$finalvardate = null;
$discID2 = null;
$status = null;  
?>
<!DOCTYPE html>
<html lang="en">
	<head>
<?php 
								$model = new Model_PlusData();
						        $model->_name  = '3dparty';						                                       
						        $toppages2 = $model->selectForArray(array('id' => '8' ), array('displayorder' => 'ASC')  );
								foreach($toppages2 as $toppage2xx):?>
<?php echo $toppage2xx->head; ?><?php endforeach; ?>
		<meta charset="utf-8">
		 <title> <?php echo $this->siteData['homepage'] ?> <?php echo $this->PageTitle ? '' . $this->PageTitle : '' ?>  </title>
        <meta name="keywords" content="<?php echo $this->siteData['keywords'] ?>" />
		<meta name="description"  content="<?php echo $this->siteData['metatag'] ?>" />
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<link rel="stylesheet" href="<?php echo THEME_DIR ?>assets/css/imports.css" media="screen">
		<link rel="stylesheet" href="<?php echo THEME_DIR ?>assets/css/bootstrap.min.css" media="screen">
		<link rel="stylesheet" href="<?php echo THEME_DIR ?>assets/css/owl-carousel.css" media="screen">
        <link rel="stylesheet" href="<?php echo THEME_DIR ?>assets/css/tour-search.css" media="screen">
          <link rel="stylesheet" href="<?php echo THEME_DIR ?>assets/css/plugins.css" media="screen">
           <link rel="stylesheet" href="<?php echo THEME_DIR ?>assets/owl-carousel/owl.carousel.css" media="screen">
               <link rel="stylesheet" href="<?php echo THEME_DIR ?>assets/owl-carousel/owl.theme.css" media="screen">
            <link rel="stylesheet" href="<?php echo THEME_DIR ?>assets/owl-carousel/owl.transitions.css" media="screen">
        <link href="<?php echo THEME_DIR ?>assets/js/owl-carousel/owl.carousel.css" rel="stylesheet" type="text/css" />
        <script src="<?php echo THEME_DIR ?>assets/n/nouislider.js"></script>
            <script src="<?php echo THEME_DIR ?>assets/n/nouislider.min.js"></script>
        <script src="<?php echo THEME_DIR ?>assets/n/nouislider.js.download.js"></script>
        
        
		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
	    <style type="text/css">
<!--
.style1 {color: #828283}
.style2 {color: #2181c4}
-->
        </style>
        
        
        <style>
#myBtn {
  display: none;
  position: fixed;
  bottom: 35px;
  right: 30px;
  z-index: 99;
  border: none;
  outline: none;
  background-color: #124273 ;
  color: white;
  cursor: pointer;
  padding: 12px;
  border-radius: 10px;
}

#myBtn:hover {
  background-color: #dc1f26;
}
</style>


        
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>

<script type="text/javascript">
function cycleImages(){
      var $active = $('#background_cycler .active');
      var $next = ($('#background_cycler .active').next().length > 0) ? $('#background_cycler .active').next() : $('#background_cycler div:first');
      $next.css('z-index',2);//move the next image up the pile
	  // $('#background_cycler').css('height','100%');
	  $active.fadeOut(1500,function(){//fade out the top image
	  $active.css('z-index',1).show().removeClass('active');//reset the z-index and unhide the image
      $next.css('z-index',3).addClass('active');//make the next image the top one
      });
    }

    $(window).load(function(){
		$('#background_cycler').fadeIn(1500);//fade the background back in once all the images are loaded
		  // run every 7s
		  setInterval('cycleImages()', 3000);
    })
</script>
</head>

	<body class="home">
<?php 
								$model = new Model_PlusData();
						        $model->_name  = '3dparty';						                                       
						        $toppages2 = $model->selectForArray(array('id' => '8' ), array('displayorder' => 'ASC')  );
								foreach($toppages2 as $toppage2xx):?>
<?php echo $toppage2xx->body; ?><?php endforeach; ?>
<button onClick="topFunction()" id="myBtn" title="Go to top">Back to Top</button>
		<div id="top"></div>

		<!-- Navigation (main menu)
		================================================== -->

 <?php
 
 if (isset($_POST["type"]) == 'add') {
  session_destroy();
        session_start(); 
 
$_SESSION['products'] =  $_COOKIE["height"] ;

 
 } 


?>



 <script  >
          function getdata11(){
createCookie("height", $(window).height(), "10");
 

 function createCookie(name, value, days) {
 var expires;
  
  var date = new Date();
   
  expires = (document.getElementById("name").value) ;
<1--  alert(expires); --> 
 
  document.cookie = escape(name) + "=" + expires  ;

 }
          
}
       </script>

		<div class="navbar-wrapper">
			<header class="navbar navbar-default navbar-fixed-top" id="MainMenu">
				<div class="navbar-extra-top clearfix" style="background:#124273 ; color:#FFFFFF">
					<div class="navbar container-fluid">
						<div class="col-md-3" style="padding:0PX; " ><h5 style="padding-top:1PX; color:#FFFFFF"> Get instant access to the best travel deals </h4></div>
                        <div class="col-md-4" style="padding-top:10px; padding-right:0px;"> 


 

 
 <form id="maillistform" method="post" action="<?php echo LANG_URL ?>addon/maillist" name="subscribe_form" role="form">

                                        <div class=" ">


                                          <div class="col-md-8" style="padding: 0px;">  
           <input class="form-control"   id="name" dir="ltr"   name="name" type="email"  value="Email Address" />  </div>
                                             <input    type="hidden" name="type" value="add" /><input name="maillist" type="hidden" value="1" />
                                        <div class="col-md-4"><input type="submit" value="Register" class="btn" style="background:#FF0000"> </div>
                                                 
                                            </button>
                                        </div>
                                    </form> 
                                    <script type="text/javascript">
                                        <!--
                                                               (function ($) {
                                            $(document).ready(function () {
                                                $('form#maillistform').submit(function (e) {
                                                    e.preventDefault();
                                                    var form = $(this);
                                                    var url = form.attr('action') + '?is_ajax=true';
                                                    var data = form.serialize();
                                                    form.find('input,textarea,select').attr('disabled', 'disabled');
                                                    $.ajax({
                                                        url: url,
                                                        data: data,
                                                        dataType: 'json',
                                                        type: 'POST',
                                                        success: function (data) {
                                                            if (data.success)
                                                            {
                                                                form.slideUp('slow', function () {
                                                                    form.html(data.message);
                                                                    form.slideDown('slow');
                                                                });
                                                            } else
                                                            {
                                                                form.find('input,textarea,select').removeAttr('disabled');
                                                                form.find('.error').remove();
                                                                if (typeof data.error.name != 'undefined')
                                                                {
                                                                    var len = data.error.name.length;
                                                                    for (var i = 0; i < len; i++)
                                                                    {
                                                                        form.find('#name').after('<div class="error" style="color:#ff0000;">' + data.error.name[i] + '</div>');
                                                                    }
                                                                }
                                                                if (typeof data.error.email != 'undefined')
                                                                {
                                                                    var len = data.error.email.length;
                                                                    for (var i = 0; i < len; i++)
                                                                    {
                                                                        form.find('#email').after('<div class="error" style="color:#ff0000;">' + data.error.email[i] + '</div>');
                                                                    }
                                                                }
                                                                form.find('.error').hide();
                                                                form.find('.error').fadeIn();
                                                            }
                                                        },
                                                        error: function () {
                                                            form.unbind('submit');
                                                            form.submit();
                                                        }
                                                    });
                                                });
                                            });
                                        })(jQuery);
                                        //-->
                                    </script>

                                             
                         </div>
						<div class="col-md-5" style="padding:0px;text-align: center; padding-top:19px; height: 64px; ">
                         <a  class="topa"  href="<?php echo LANG_URL ?>"> Home</a>    
 
                         <?php
 
								$model = new Model_PlusData();
						        $model->_name  = 'pages';						                                       
						        $toppages = $model->selectForArray(array('top' => '1'    ), array('displayorder' => 'ASC')  );
								foreach($toppages as $toppage):
								   
							?>

  <i style="padding: 5px; color:#FFFFFF" > | </i>

<a  class="topa" 
<?php if($toppage->type2 == 'text'  ): ?>
 href="<?php echo LANG_URL ?><?php echo (trim($toppage->pagurl)?'mainlyeurope/'.trim($toppage->pagurl):'page/v/i/'.$toppage->id) ?>" 
<?php elseif($toppage->type2 == 'textdrop'  ): ?>

<?php
 
								$model = new Model_PlusData();
						        $model->_name  = 'pages';						                                       
						        $toppages77 = $model->selectForArray(array('pageid' => $toppage->id  ), array('displayorder' => 'ASC') , 1 );
								foreach($toppages77 as $toppage77):
								   
							?>
href="<?php echo LANG_URL ?><?php echo (trim($toppage77->pagurl)?'mainlyeurope/'.trim($toppage77->pagurl):'page/v/i/'.$toppage77->id) ?>" 

<?php endforeach; ?>


<?php endif; ?> >
<?php echo $toppage->title ?>   

</a> 
						 
                             
                             <?php endforeach; ?>   
                          
										 <i style="padding: 5px; color:#FFFFFF" > | </i>
 <a class="topa" button onclick="myFunction2()"  href="" target="_blank"> Passports & Visas</a> 

<i style="padding: 5px; color:#FFFFFF" > | </i>
 <a  class="topa" button onclick="myFunction()"  href=""  target="_blank" > View My Booking</a>  
			
 
<script>
function myFunction() {
    window.open("https://tours.mainlyeurope.com/Account/LogOn?ReturnUrl=%2f");
}
</script>

<script>
function myFunction2() {
    window.open("http://www.visahq.com/?a_aid=vaff10075");
}
</script>
					  </div>
                      
					
						
					</div>
				</div>

				<div class="container-fluid collapse-md" id="navbar-main-container">
					<div class="col-md-3 navbar-header" style="padding-right: 0px;">
	<a href="<?php echo LANG_URL ?>index.php" style="padding-left:0px;" class="navbar-brand"><img style="margin-top:-12px;"  src="<?php echo THEME_DIR ?>assets/images/logo.png"> </a>
						
						 
						<button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
					</div>

					<nav class="col-md-7 navbar-collapse collapse" id="navbar-main">
                     
						<ul class="nav navbar-nav navbar-right">
							 <li class="dropdown show-on-hover">
								<a class="dropdown-toggle" data-toggle="dropdown" href="#">Destinations </a>
								<ul class="dropdown-menu">
                                         
                              <?php
 
								$model = new Model_PlusData();
						        $model->_name  = 'region';						                                       
						        $toppages = $model->selectForArray(array(), array('displayorder' => 'ASC')  );
								foreach($toppages as $toppage):
									   
							?>
								    <div class="col-md-3" style="" >
                          <h4  style="color:#999999;border-bottom: 1px solid #fff;padding-bottom: 5px;font-family:main" > <?php echo $toppage->title; ?> </h4>	
                                    <?php
 
								$model = new Model_PlusData();
						        $model->_name  = 'country';						                                       
						        $toppages2 = $model->selectForArray(array('regionid' => $toppage->id), array('displayorder' => 'ASC')  );
								foreach($toppages2 as $toppage2):
									   
							?>  
										
							<?php
							$tempwwaac4x4 = array(); ?>
							<?php 
								$model = new Model_PlusData();
						        $model->_name  = 'items';						                                       
			  $toppages2item = $model->selectForArray(array('countryid' => $toppage2->id , 'inactive' => '0' ,'regionid = ?' =>  '0'  ), array('displayorder' => 'ASC')  );
								foreach($toppages2item as $toppage2items):
									   
							?> 
							 <?php $tempwwaac4x4 []= $toppage2items->id ?> 
							 <?php endforeach; ?>
							 
							 	<?php 
								$model = new Model_PlusData();
						        $model->_name  = 'items';						                                       
						        $toppages2item = $model->selectForArray(array('countryid2' => $toppage2->id , 'inactive' => '0'  ,'regionid2 = ?' =>  '0'  ), array('displayorder' => 'ASC')  );
								foreach($toppages2item as $toppage2items):
									   
							?> 
							 <?php $tempwwaac4x4 []= $toppage2items->id ?> 
							 <?php endforeach; ?>
							 
							 
							 	<?php 
								$model = new Model_PlusData();
						        $model->_name  = 'items';						                                       
						        $toppages2item = $model->selectForArray(array('countryid3' => $toppage2->id , 'inactive' => '0'  ,'regionid3 = ?' =>  '0'  ), array('displayorder' => 'ASC')  );
								foreach($toppages2item as $toppage2items):
									   
							?> 
							 <?php $tempwwaac4x4 []= $toppage2items->id ?> 
							 <?php endforeach; ?>
							 
							 
							 	<?php 
								$model = new Model_PlusData();
						        $model->_name  = 'items';						                                       
						        $toppages2item = $model->selectForArray(array('countryid4' => $toppage2->id , 'inactive' => '0'  ,'regionid4 = ?' =>  '0'  ), array('displayorder' => 'ASC')  );
								foreach($toppages2item as $toppage2items):
									   
							?> 
							 <?php $tempwwaac4x4 []= $toppage2items->id ?> 
							 <?php endforeach; ?>
							 
							 
							 	<?php 
								$model = new Model_PlusData();
						        $model->_name  = 'items';						                                       
						        $toppages2item = $model->selectForArray(array('countryid5' => $toppage2->id , 'inactive' => '0'  ,'regionid5 = ?' =>  '0'  ), array('displayorder' => 'ASC')  );
								foreach($toppages2item as $toppage2items):
									   
							?> 
							 <?php $tempwwaac4x4 []= $toppage2items->id ?> 
							 <?php endforeach; ?>
							 
							 
							 	<?php 
								$model = new Model_PlusData();
						        $model->_name  = 'items';						                                       
						        $toppages2item = $model->selectForArray(array('countryid6' => $toppage2->id , 'inactive' => '0'  ,'regionid6 = ?' =>  '0'  ), array('displayorder' => 'ASC')  );
								foreach($toppages2item as $toppage2items):
									   
							?> 
							 <?php $tempwwaac4x4 []= $toppage2items->id ?> 
							 <?php endforeach; ?>
							 
							 
							 
							 	<?php 
								$model = new Model_PlusData();
						        $model->_name  = 'items';						                                       
						        $toppages2item = $model->selectForArray(array('countryid7' => $toppage2->id , 'inactive' => '0'  ,'regionid7 = ?' =>  '0'  ), array('displayorder' => 'ASC')  );
								foreach($toppages2item as $toppage2items):
									   
							?> 
							 <?php $tempwwaac4x4 []= $toppage2items->id ?> 
							 <?php endforeach; ?>
							 
							  
							 <?php $countcontry =  count($tempwwaac4x4);
							 if($countcontry != 0  ) : 
							 
							 ; ?>
							  
							
									<li style="padding-bottom: 5px;" ><a style="color:#FFFFFF"  href="<?php echo LANG_URL ?><?php echo (trim($toppage2->pagurl)?'europe-vacations/'.trim($toppage2->pagurl):'country/v/i/'.$toppage2->id) ?>"><?php echo $toppage2->data; ?>  </a></li>
									<?php endif; ?>
<?php endforeach; ?>
									</div>
                                    <?php endforeach; ?>
                                    
                                  
                                    
                                <div class="col-md-12"  style="color:#fff" ><div class="bannermenu" >
 <?php
 
								$model = new Model_PlusData();
						        $model->_name  = 'boxes';						                                       
						        $toppages2 = $model->selectForArray(array('id' => '8' ), array('displayorder' => 'ASC')  );
								foreach($toppages2 as $toppage2xx):
									   
							?> 

								 <div class="col-md-8" style="padding-top:20px;"  > <?php echo $toppage2xx->data; ?> </div>
                                 <div class="col-md-4" style="padding-top:20px;"  ><img style="margin-top:px;padding-bottom:20px;  "  src="<?php echo constant('APP_BASEURL') . '/MyUpload/' . $toppage2xx->thumb ?>"> </div> 
								
                                <?php endforeach; ?>
								
								</div></div>
								
								 
									 
								 
								</ul>

							</li> 
 
  
  <?php
 
								$model = new Model_PlusData();
						        $model->_name  = 'pages';						                                       
						        $toppages = $model->selectForArray(array('menu' => '1'    ), array('displayorder' => 'ASC')  );
								foreach($toppages as $toppage):
								   
							?>


							<li><a href="<?php echo LANG_URL ?><?php echo (trim($toppage->pagurl)?'mainlyeurope/'.trim($toppage->pagurl):'page/v/i/'.$toppage->id) ?>"> <?php echo $toppage->title ?>  </a></li>
                             
                             <?php endforeach; ?>
                         
						</ul>
                       
					</nav>
                <div class="heddennn col-md-2" style="padding: 0px;text-align: right;padding-top: 10px;">    <div class="fa fa-phone" style="color:#dc1f26; font-size: 20px;margin-top: 15px;padding-left: 10px;"></div> <spam style="color:#124273;font-size: 23px;  "><strong>  <?php echo $this->siteData['phone'] ?></strong> </spam>  </div>
                   
				</div><!-- /.container-fluid -->
			</header>
		</div><!-- /.navbar-wrapper -->
		
	
	
	
		
	 
   
 <?php foreach($this->Item as $value): ?>
  <style type="text/css">
<!--
.style1 {color: #828283}
.style2 {color: #2181c4}
-->

.complete{
    display:none;
}

.more{
       background: #dc1f26;
    color: navy;
    font-size: 16px;
   
    cursor: pointer;
    padding: 10px;
    color: #fff;
    float: right;
    margin-right: 10px;
}


</style>


<style>
#myBtn {
  display: none;
  position: fixed;
  bottom: 35px;
  right: 30px;
  z-index: 99;
  border: none;
  outline: none;
  background-color: #124273 ;
  color: white;
  cursor: pointer;
  padding: 12px;
  border-radius: 10px;
}

#myBtn:hover {
  background-color: #dc1f26;
}
</style>

 
	<!-- Hero Section
		================================================== -->
		<section class="hero small-hero" >
			<div class="bg-overlay">
				<div class="container" style="">
					  
			  </div>
			</div>
		</section>


		<!-- Main Section
		================================================== -->
        
        <section class="">
			<div class="container">
             <div class="col-sm-6"><h2><?php echo $value->data; ?> <spam style="color:#dc1f26" > Vacations </spam></h2> </div>
             <div class="col-sm-6" style="text-align: right;padding-top: 20px;">
  </div>
             
              <div class="col-sm-12">  <?php echo $value->description; ?>
 </div>

</div></section>
		<section class="main" style="padding-top:20px;" >
			<div class="container">

				  
        <div class="container">
    <div class="griddx well well-sm">
        
        <div class=" btn-group">
            <a href="#"  style="    background: #dc1f26;" id="list" class="griddx btn btn-default btn-sm"><span class="glyphicon glyphicon-th-list">
            </span> </a> <a style="background: #114172;" href="#" id="grid" class="griddx btn btn-default btn-sm"><span
                class="glyphicon glyphicon-th"></span> </a>
        </div>
    </div>
    <div id="products" class="row list-group">
                                        <?php
 
								$model = new Model_PlusData();
						        $model->_name  = 'items';						                                       
						        $toppages2 = $model->selectForArray(array('countryid' => $value->id , 'inactive' => '0'), array('displayorder' => 'ASC')  );
								foreach($toppages2 as $toppage2):
									   
							?>  

    
          <div class="item col-sm-4">
                                             
							<article class="place-box card">
					 <?php
 
								$model = new Model_PlusData();
						        $model->_name  = 'label';						                                       
						        $toppages27 = $model->selectForArray(array('id' => $toppage2->labelid), array('displayorder' => 'ASC') , 1 );
								foreach($toppages27 as $toppage27):
									   
							?>  		
							
    <img  style="position:absolute" src="<?php echo  APP_BASEURL.'/MyUpload/'.$toppage27->image ?>"  width="96" height="91" border="0" class="corner">
	<?php endforeach; ?>
	
	
								<a href="<?php echo LANG_URL ?><?php echo (trim($toppage2->pagurl)?'vacations/'.trim($toppage2->pagurl):'item/v/i/'.$toppage2->id) ?>" class="">
									 
									<div class="entry-thumbnail"> 
		 <img style="margin-right:10px;" width="400" height="250"  style="margin-right:10px;"   src="<?php echo  APP_BASEURL.'/MyUpload/'.$toppage2->thumb ?>">

 				
 
 </div>
							  </a>
                              <div style="padding: 1px 15px 4px; z-index: 1; bottom: 0;background: #f2f2f2;border-radius: 0 0 6px 6px; ">
                              <h3 class="headerrr"><a href="<?php echo LANG_URL ?><?php echo (trim($toppage2->pagurl)?'vacations/'.trim($toppage2->pagurl):'item/v/i/'.$toppage2->id) ?>" ><?php echo $toppage2->title; ?> </a> </h3>
                              <div class="blockpackagehome" ><?php echo $toppage2->shortdescription; ?>  </div>
                           <div style="border-bottom:1px solid #d0d0d0; padding-bottom:30px;">   <?php echo $toppage2->daynumber; ?> days 


<?php if(trim($toppage2->prize2)): ?>  <spam style="color:#dc1f26;"> From </spam>	    

   <!-- vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv  start from  - discount   ------------------------ --> 
				   
				   
				 <?php 
        $modelBlocks = new Model_PlusData();
        $modelBlocks->_name = 'discount';
        $toppages = $modelBlocks->selectForArray(array( ), array('displayorder' => 'ASC')  );
        $pagesrow=  $toppages->count();
?> <?php $numberdiscounr =  $pagesrow ;  ?> 


 
<?php if(trim($toppage2->newprice2)) : ?> <?php   $finalvar = $toppage2->newprice2 ;  ?>  

<?php elseif(!trim($toppage2->newprice2) && $numberdiscounr != '0' ) : ?> 
<!--         //////////////////////////////////////////////////////////////// --> 
 
 <?php  
     $disc  ;
 $discID  ;


 								$model = new Model_PlusData();
						        $model->_name  = 'discount';						                                       
						        $toppagesc = $model->selectForArray(array( ), array('id' => 'ASC')   );
								foreach($toppagesc as $toppage2c):		   
							?> 
 
<?php if($toppage2c->type == 'All'): ?> <?php  $disc = $toppage2c->discount ; ?> <?php  $discID = $toppage2c->id; ?>  
<!--         region////////////------------------/// --> 
<?php elseif($toppage2c->type == 'Region'): ?>  
<?php 

$regionarray = array();
          $images = explode('||',trim($toppage2c->ids,'|'));
            foreach($images as $index=>$photo): if(!trim($photo) ) continue;?>

<?php $regionarray []= $photo ?>  <?php endforeach; ?> 
<?php if(in_array($toppage2->regionid, $regionarray )): ?><?php   $disc = $toppage2c->discount ; ?> <?php  $discID = $toppage2c->id; ?>    <?php endif; ?>
<!--         region/////////////-----------------// --> 


<?php elseif($toppage2c->type == 'Country'): ?>  
<?php 

$countryarray = array();
          $images22c = explode('||',trim($toppage2c->ids,'|'));
            foreach($images22c as $photocc): if(!trim($photocc) ) continue;?>

<?php $countryarray []= $photocc ?>  <?php endforeach; ?> 
<?php if(in_array($toppage2->countryid, $countryarray )): ?><?php   $disc = $toppage2c->discount ; ?> <?php  $discID = $toppage2c->id; ?>   <?php endif; ?>

<!--         country/////////////-----------------// --> 
 

<?php elseif($toppage2c->type == 'Package'): ?>  
<?php 

$packagesarray = array();
          $images22p = explode('||',trim($toppage2c->ids,'|'));
            foreach($images22p as $photopp): if(!trim($photopp) ) continue;?>

<?php $packagesarray []= $photopp ?>  <?php endforeach; ?> 
<?php if(in_array($toppage2->id, $packagesarray )): ?><?php   $disc = $toppage2c->discount ; ?><?php  $discID = $toppage2c->id; ?>  <?php endif; ?>

<?php else: ?><?php   $disc = '' ; $discID = '' ;     ?>

<?php endif; ?>

<?php endforeach; ?>
 
 
<?php if(trim($disc)): ?> <?php   $finalvar = $toppage2->prize2 - $disc ;   ?>  
<?php elseif(!trim($disc)): ?> <?php     $finalvar = $disc ; ?>  
<?php endif; ?>
 
<!--         //////////////////////////////////////////////////////////////// --> 

<?php else :?>  <?php  $finalvar = ''  ;   ?> 
<?php endif; ?>
 
 

 <spam <?php if(trim($finalvar)): ?><?php echo 'style="color:#000;text-decoration: line-through;" ' ?> <?php elseif(!trim($finalvar)): ?><?php echo 'style="color:#dc1f26;" ' ?><?php endif; ?>  >  $<?php echo number_format($toppage2->prize2) ?>   </spam> 


 <?php if(trim($finalvar)): ?>  <spam style="color:#dc1f26; padding-left:8px;" >   <?php echo '$'. number_format($finalvar) ;?> </spam>
  <?php endif; ?> 

	 <!-- vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv  start from  - discount   ------------------------ --> 

<?
$disc = null;
$discID = null;
$finalvar = null;
$discDATE = null;
$finalvardate = null;
$discID2 = null;
$status = null;  ?>

<?php endif; ?> <br/> 
<?php echo $toppage2->pricedescription; ?>  </div>
<div style="text-align:right; float:right; padding-top: 2px; "> 
<a   href="<?php echo LANG_URL ?><?php echo (trim($toppage2->pagurl)?'vacations/'.trim($toppage2->pagurl):'item/v/i/'.$toppage2->id) ?>" > More >>   </a> </div>
<div style="text-align:left; color:#28272F;    height: 27px;  padding-top: 2px;">  
 <?php echo $toppage2->ptdpage; ?>   </div>
</div>
							</article>
                           
						</div>
                        
                        
                        <?php endforeach; ?>
                          
                    
                            
                        <!--  //////////////////////////////////////////////////////////// -->


 <?php
 
								$model = new Model_PlusData();
						        $model->_name  = 'items';						                                       
						        $toppages2 = $model->selectForArray(array('countryid2' => $value->id , 'inactive' => '0'), array('displayorder' => 'ASC')  );
								foreach($toppages2 as $toppage2):
									   
							?>  

    <?php if( $toppage2->regionid2 != '0'): ?> 
          <div class="item col-sm-4">
                                             
							<article class="place-box card">
					 <?php
 
								$model = new Model_PlusData();
						        $model->_name  = 'label';						                                       
						        $toppages27 = $model->selectForArray(array('id' => $toppage2->labelid), array('displayorder' => 'ASC') , 1 );
								foreach($toppages27 as $toppage27):
									   
							?>  		
							
    <img  style="position:absolute" src="<?php echo  APP_BASEURL.'/MyUpload/'.$toppage27->image ?>"  width="96" height="91" border="0" class="corner">
	<?php endforeach; ?>
	
	
								<a href="<?php echo LANG_URL ?><?php echo (trim($toppage2->pagurl)?'vacations/'.trim($toppage2->pagurl):'item/v/i/'.$toppage2->id) ?>" class="">
									 
									<div class="entry-thumbnail"> 
		 <img style="margin-right:10px;" width="400" height="250"  style="margin-right:10px;"   src="<?php echo  APP_BASEURL.'/MyUpload/'.$toppage2->thumb ?>">

 				
 
 </div>
							  </a>
                              <div style="padding: 1px 15px 4px; z-index: 1; bottom: 0;background: #f2f2f2;border-radius: 0 0 6px 6px;">
                              <h3 class="headerrr" ><a href="<?php echo LANG_URL ?><?php echo (trim($toppage2->pagurl)?'vacations/'.trim($toppage2->pagurl):'item/v/i/'.$toppage2->id) ?>" ><?php echo $toppage2->title; ?> </a> </h3>
                              <div class="blockpackagehome" > <?php echo $toppage2->shortdescription; ?>  </div>
                           <div style="border-bottom:1px solid #d0d0d0; padding-bottom:30px;">   <?php echo $toppage2->daynumber; ?> days  
 

<?php if(trim($toppage2->prize2)): ?>  <spam style="color:#dc1f26;"> From </spam>	    

   <!-- vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv  start from  - discount   ------------------------ --> 
				   
				   
				 <?php 
        $modelBlocks = new Model_PlusData();
        $modelBlocks->_name = 'discount';
        $toppages = $modelBlocks->selectForArray(array( ), array('displayorder' => 'ASC')  );
        $pagesrow=  $toppages->count();
?> <?php $numberdiscounr =  $pagesrow ;  ?> 


 
<?php if(trim($toppage2->newprice2)) : ?> <?php   $finalvar = $toppage2->newprice2 ;  ?>  

<?php elseif(!trim($toppage2->newprice2) && $numberdiscounr != '0' ) : ?> 
<!--         //////////////////////////////////////////////////////////////// --> 
 
 <?php  
     $disc  ;
 $discID  ;


 								$model = new Model_PlusData();
						        $model->_name  = 'discount';						                                       
						        $toppagesc = $model->selectForArray(array( ), array('id' => 'ASC')   );
								foreach($toppagesc as $toppage2c):		   
							?> 
 
<?php if($toppage2c->type == 'All'): ?> <?php  $disc = $toppage2c->discount ; ?> <?php  $discID = $toppage2c->id; ?>  
<!--         region////////////------------------/// --> 
<?php elseif($toppage2c->type == 'Region'): ?>  
<?php 

$regionarray = array();
          $images = explode('||',trim($toppage2c->ids,'|'));
            foreach($images as $index=>$photo): if(!trim($photo) ) continue;?>

<?php $regionarray []= $photo ?>  <?php endforeach; ?> 
<?php if(in_array($toppage2->regionid, $regionarray )): ?><?php   $disc = $toppage2c->discount ; ?> <?php  $discID = $toppage2c->id; ?>    <?php endif; ?>
<!--         region/////////////-----------------// --> 


<?php elseif($toppage2c->type == 'Country'): ?>  
<?php 

$countryarray = array();
          $images22c = explode('||',trim($toppage2c->ids,'|'));
            foreach($images22c as $photocc): if(!trim($photocc) ) continue;?>

<?php $countryarray []= $photocc ?>  <?php endforeach; ?> 
<?php if(in_array($toppage2->countryid, $countryarray )): ?><?php   $disc = $toppage2c->discount ; ?> <?php  $discID = $toppage2c->id; ?>   <?php endif; ?>

<!--         country/////////////-----------------// --> 
 

<?php elseif($toppage2c->type == 'Package'): ?>  
<?php 

$packagesarray = array();
          $images22p = explode('||',trim($toppage2c->ids,'|'));
            foreach($images22p as $photopp): if(!trim($photopp) ) continue;?>

<?php $packagesarray []= $photopp ?>  <?php endforeach; ?> 
<?php if(in_array($toppage2->id, $packagesarray )): ?><?php   $disc = $toppage2c->discount ; ?><?php  $discID = $toppage2c->id; ?>  <?php endif; ?>

<?php else: ?><?php   $disc = '' ; $discID = '' ;     ?>

<?php endif; ?>

<?php endforeach; ?>
 
 
<?php if(trim($disc)): ?> <?php   $finalvar = $toppage2->prize2 - $disc ;   ?>  
<?php elseif(!trim($disc)): ?> <?php     $finalvar = $disc ; ?>  
<?php endif; ?>
 
<!--         //////////////////////////////////////////////////////////////// --> 

<?php else :?>  <?php  $finalvar = ''  ;   ?> 
<?php endif; ?>
 
 

 <spam <?php if(trim($finalvar)): ?><?php echo 'style="color:#000;text-decoration: line-through;" ' ?> <?php elseif(!trim($finalvar)): ?><?php echo 'style="color:#dc1f26;" ' ?><?php endif; ?>  >  $<?php echo number_format($toppage2->prize2) ?>   </spam> 


 <?php if(trim($finalvar)): ?>  <spam style="color:#dc1f26; padding-left:8px;" >   <?php echo '$'. number_format($finalvar) ;?> </spam>
  <?php endif; ?> 

	 <!-- vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv  start from  - discount   ------------------------ --> 

<?
$disc = null;
$discID = null;
$finalvar = null;
$discDATE = null;
$finalvardate = null;
$discID2 = null;
$status = null;  ?>

<?php endif; ?> <br/> 
<?php echo $toppage2->pricedescription; ?>  </div>
<div style="text-align:right; float:right;padding-top: 2px;  "> 
<a   href="<?php echo LANG_URL ?><?php echo (trim($toppage2->pagurl)?'vacations/'.trim($toppage2->pagurl):'item/v/i/'.$toppage2->id) ?>" > More >>   </a> </div>
<div style="text-align:left; color:#28272F;height: 27px;padding-top: 2px; ">  
 <?php echo $toppage2->ptdpage; ?>   </div>
</div>
							</article>
                           
						</div>
                        
                      
                        <?php endif; ?> 
 
                        <?php endforeach; ?>

  <!--  //////////////////////////////////////////////////////////// -->















<!--  //////////////////////////////////////////////////////////// -->


 <?php
 
								$model = new Model_PlusData();
						        $model->_name  = 'items';						                                       
						        $toppages2 = $model->selectForArray(array('countryid3' => $value->id , 'inactive' => '0'), array('displayorder' => 'ASC')  );
								foreach($toppages2 as $toppage2):
									   
							?>  

    <?php if( $toppage2->regionid3 != '0'): ?> 
          <div class="item col-sm-4">
                                             
							<article class="place-box card">
					 <?php
 
								$model = new Model_PlusData();
						        $model->_name  = 'label';						                                       
						        $toppages27 = $model->selectForArray(array('id' => $toppage2->labelid), array('displayorder' => 'ASC') , 1 );
								foreach($toppages27 as $toppage27):
									   
							?>  		
							
    <img  style="position:absolute" src="<?php echo  APP_BASEURL.'/MyUpload/'.$toppage27->image ?>"  width="96" height="91" border="0" class="corner">
	<?php endforeach; ?>
	
	
								<a href="<?php echo LANG_URL ?><?php echo (trim($toppage2->pagurl)?'vacations/'.trim($toppage2->pagurl):'item/v/i/'.$toppage2->id) ?>" class="">
									 
									<div class="entry-thumbnail"> 
		 <img style="margin-right:10px;" width="400" height="250"  style="margin-right:10px;"   src="<?php echo  APP_BASEURL.'/MyUpload/'.$toppage2->thumb ?>">

 				
 
 </div>
							  </a>
                              <div style="padding: 1px 15px 4px; z-index: 1; bottom: 0;background: #f2f2f2;border-radius: 0 0 6px 6px;">
                              <h3 class="headerrr" ><a href="<?php echo LANG_URL ?><?php echo (trim($toppage2->pagurl)?'vacations/'.trim($toppage2->pagurl):'item/v/i/'.$toppage2->id) ?>" ><?php echo $toppage2->title; ?> </a> </h3>
                              <div class="blockpackagehome" > <?php echo $toppage2->shortdescription; ?>  </div>
                           <div style="border-bottom:1px solid #d0d0d0; padding-bottom:30px;">   <?php echo $toppage2->daynumber; ?> days 
<?php if(trim($toppage2->prize2)): ?>  <spam style="color:#dc1f26;"> From </spam>	    

   <!-- vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv  start from  - discount   ------------------------ --> 
				   
				   
				 <?php 
        $modelBlocks = new Model_PlusData();
        $modelBlocks->_name = 'discount';
        $toppages = $modelBlocks->selectForArray(array( ), array('displayorder' => 'ASC')  );
        $pagesrow=  $toppages->count();
?> <?php $numberdiscounr =  $pagesrow ;  ?> 


 
<?php if(trim($toppage2->newprice2)) : ?> <?php   $finalvar = $toppage2->newprice2 ;  ?>  

<?php elseif(!trim($toppage2->newprice2) && $numberdiscounr != '0' ) : ?> 
<!--         //////////////////////////////////////////////////////////////// --> 
 
 <?php  
     $disc  ;
 $discID  ;


 								$model = new Model_PlusData();
						        $model->_name  = 'discount';						                                       
						        $toppagesc = $model->selectForArray(array( ), array('id' => 'ASC')   );
								foreach($toppagesc as $toppage2c):		   
							?> 
 
<?php if($toppage2c->type == 'All'): ?> <?php  $disc = $toppage2c->discount ; ?> <?php  $discID = $toppage2c->id; ?>  
<!--         region////////////------------------/// --> 
<?php elseif($toppage2c->type == 'Region'): ?>  
<?php 

$regionarray = array();
          $images = explode('||',trim($toppage2c->ids,'|'));
            foreach($images as $index=>$photo): if(!trim($photo) ) continue;?>

<?php $regionarray []= $photo ?>  <?php endforeach; ?> 
<?php if(in_array($toppage2->regionid, $regionarray )): ?><?php   $disc = $toppage2c->discount ; ?> <?php  $discID = $toppage2c->id; ?>    <?php endif; ?>
<!--         region/////////////-----------------// --> 


<?php elseif($toppage2c->type == 'Country'): ?>  
<?php 

$countryarray = array();
          $images22c = explode('||',trim($toppage2c->ids,'|'));
            foreach($images22c as $photocc): if(!trim($photocc) ) continue;?>

<?php $countryarray []= $photocc ?>  <?php endforeach; ?> 
<?php if(in_array($toppage2->countryid, $countryarray )): ?><?php   $disc = $toppage2c->discount ; ?> <?php  $discID = $toppage2c->id; ?>   <?php endif; ?>

<!--         country/////////////-----------------// --> 
 

<?php elseif($toppage2c->type == 'Package'): ?>  
<?php 

$packagesarray = array();
          $images22p = explode('||',trim($toppage2c->ids,'|'));
            foreach($images22p as $photopp): if(!trim($photopp) ) continue;?>

<?php $packagesarray []= $photopp ?>  <?php endforeach; ?> 
<?php if(in_array($toppage2->id, $packagesarray )): ?><?php   $disc = $toppage2c->discount ; ?><?php  $discID = $toppage2c->id; ?>  <?php endif; ?>

<?php else: ?><?php   $disc = '' ; $discID = '' ;     ?>

<?php endif; ?>

<?php endforeach; ?>
 
 
<?php if(trim($disc)): ?> <?php   $finalvar = $toppage2->prize2 - $disc ;   ?>  
<?php elseif(!trim($disc)): ?> <?php     $finalvar = $disc ; ?>  
<?php endif; ?>
 
<!--         //////////////////////////////////////////////////////////////// --> 

<?php else :?>  <?php  $finalvar = ''  ;   ?> 
<?php endif; ?>
 
 

 <spam <?php if(trim($finalvar)): ?><?php echo 'style="color:#000;text-decoration: line-through;" ' ?> <?php elseif(!trim($finalvar)): ?><?php echo 'style="color:#dc1f26;" ' ?><?php endif; ?>  >  $<?php echo number_format($toppage2->prize2) ?>   </spam> 


 <?php if(trim($finalvar)): ?>  <spam style="color:#dc1f26; padding-left:8px;" >   <?php echo '$'. number_format($finalvar) ;?> </spam>
  <?php endif; ?> 

	 <!-- vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv  start from  - discount   ------------------------ --> 

<?
$disc = null;
$discID = null;
$finalvar = null;
$discDATE = null;
$finalvardate = null;
$discID2 = null;
$status = null;  ?>

<?php endif; ?> <br/> 
<?php echo $toppage2->pricedescription; ?>  </div>
<div style="text-align:right; float:right;padding-top: 2px;  "> 
<a   href="<?php echo LANG_URL ?><?php echo (trim($toppage2->pagurl)?'vacations/'.trim($toppage2->pagurl):'item/v/i/'.$toppage2->id) ?>" > More >>   </a> </div>
<div style="text-align:left; color:#28272F;height: 27px;padding-top: 2px; ">  
 <?php echo $toppage2->ptdpage; ?>   </div>
</div>
							</article>
                           
						</div>
                        
                      
                        <?php endif; ?> 
 
                        <?php endforeach; ?>







<!--  //////////////////////////////////////////////////////////// -->


 <?php
 
								$model = new Model_PlusData();
						        $model->_name  = 'items';						                                       
						        $toppages2 = $model->selectForArray(array('countryid4' => $value->id , 'inactive' => '0'), array('displayorder' => 'ASC')  );
								foreach($toppages2 as $toppage2):
									   
							?>  

    <?php if( $toppage2->regionid4 != '0'): ?> 
          <div class="item col-sm-4">
                                             
							<article class="place-box card">
					 <?php
 
								$model = new Model_PlusData();
						        $model->_name  = 'label';						                                       
						        $toppages27 = $model->selectForArray(array('id' => $toppage2->labelid), array('displayorder' => 'ASC') , 1 );
								foreach($toppages27 as $toppage27):
									   
							?>  		
							
    <img  style="position:absolute" src="<?php echo  APP_BASEURL.'/MyUpload/'.$toppage27->image ?>"  width="96" height="91" border="0" class="corner">
	<?php endforeach; ?>
	
	
								<a href="<?php echo LANG_URL ?><?php echo (trim($toppage2->pagurl)?'vacations/'.trim($toppage2->pagurl):'item/v/i/'.$toppage2->id) ?>" class="">
									 
									<div class="entry-thumbnail"> 
		 <img style="margin-right:10px;" width="400" height="250"  style="margin-right:10px;"   src="<?php echo  APP_BASEURL.'/MyUpload/'.$toppage2->thumb ?>">

 				
 
 </div>
							  </a>
                              <div style="padding: 1px 15px 4px; z-index: 1; bottom: 0;background: #f2f2f2;border-radius: 0 0 6px 6px;">
                              <h3 class="headerrr" ><a href="<?php echo LANG_URL ?><?php echo (trim($toppage2->pagurl)?'vacations/'.trim($toppage2->pagurl):'item/v/i/'.$toppage2->id) ?>" ><?php echo $toppage2->title; ?> </a> </h3>
                              <div class="blockpackagehome" > <?php echo $toppage2->shortdescription; ?>  </div>
                           <div style="border-bottom:1px solid #d0d0d0; padding-bottom:30px;">   <?php echo $toppage2->daynumber; ?> days 

<?php if(trim($toppage2->prize2)): ?>  <spam style="color:#dc1f26;"> From </spam>	    

   <!-- vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv  start from  - discount   ------------------------ --> 
				   
				   
				 <?php 
        $modelBlocks = new Model_PlusData();
        $modelBlocks->_name = 'discount';
        $toppages = $modelBlocks->selectForArray(array( ), array('displayorder' => 'ASC')  );
        $pagesrow=  $toppages->count();
?> <?php $numberdiscounr =  $pagesrow ;  ?> 


 
<?php if(trim($toppage2->newprice2)) : ?> <?php   $finalvar = $toppage2->newprice2 ;  ?>  

<?php elseif(!trim($toppage2->newprice2) && $numberdiscounr != '0' ) : ?> 
<!--         //////////////////////////////////////////////////////////////// --> 
 
 <?php  
     $disc  ;
 $discID  ;


 								$model = new Model_PlusData();
						        $model->_name  = 'discount';						                                       
						        $toppagesc = $model->selectForArray(array( ), array('id' => 'ASC')   );
								foreach($toppagesc as $toppage2c):		   
							?> 
 
<?php if($toppage2c->type == 'All'): ?> <?php  $disc = $toppage2c->discount ; ?> <?php  $discID = $toppage2c->id; ?>  
<!--         region////////////------------------/// --> 
<?php elseif($toppage2c->type == 'Region'): ?>  
<?php 

$regionarray = array();
          $images = explode('||',trim($toppage2c->ids,'|'));
            foreach($images as $index=>$photo): if(!trim($photo) ) continue;?>

<?php $regionarray []= $photo ?>  <?php endforeach; ?> 
<?php if(in_array($toppage2->regionid, $regionarray )): ?><?php   $disc = $toppage2c->discount ; ?> <?php  $discID = $toppage2c->id; ?>    <?php endif; ?>
<!--         region/////////////-----------------// --> 


<?php elseif($toppage2c->type == 'Country'): ?>  
<?php 

$countryarray = array();
          $images22c = explode('||',trim($toppage2c->ids,'|'));
            foreach($images22c as $photocc): if(!trim($photocc) ) continue;?>

<?php $countryarray []= $photocc ?>  <?php endforeach; ?> 
<?php if(in_array($toppage2->countryid, $countryarray )): ?><?php   $disc = $toppage2c->discount ; ?> <?php  $discID = $toppage2c->id; ?>   <?php endif; ?>

<!--         country/////////////-----------------// --> 
 

<?php elseif($toppage2c->type == 'Package'): ?>  
<?php 

$packagesarray = array();
          $images22p = explode('||',trim($toppage2c->ids,'|'));
            foreach($images22p as $photopp): if(!trim($photopp) ) continue;?>

<?php $packagesarray []= $photopp ?>  <?php endforeach; ?> 
<?php if(in_array($toppage2->id, $packagesarray )): ?><?php   $disc = $toppage2c->discount ; ?><?php  $discID = $toppage2c->id; ?>  <?php endif; ?>

<?php else: ?><?php   $disc = '' ; $discID = '' ;     ?>

<?php endif; ?>

<?php endforeach; ?>
 
 
<?php if(trim($disc)): ?> <?php   $finalvar = $toppage2->prize2 - $disc ;   ?>  
<?php elseif(!trim($disc)): ?> <?php     $finalvar = $disc ; ?>  
<?php endif; ?>
 
<!--         //////////////////////////////////////////////////////////////// --> 

<?php else :?>  <?php  $finalvar = ''  ;   ?> 
<?php endif; ?>
 
 

 <spam <?php if(trim($finalvar)): ?><?php echo 'style="color:#000;text-decoration: line-through;" ' ?> <?php elseif(!trim($finalvar)): ?><?php echo 'style="color:#dc1f26;" ' ?><?php endif; ?>  >  $<?php echo number_format($toppage2->prize2) ?>   </spam> 


 <?php if(trim($finalvar)): ?>  <spam style="color:#dc1f26; padding-left:8px;" >   <?php echo '$'. number_format($finalvar) ;?> </spam>
  <?php endif; ?> 

	 <!-- vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv  start from  - discount   ------------------------ --> 

<?
$disc = null;
$discID = null;
$finalvar = null;
$discDATE = null;
$finalvardate = null;
$discID2 = null;
$status = null;  ?>

<?php endif; ?> <br/> 
<?php echo $toppage2->pricedescription; ?>  </div>
<div style="text-align:right; float:right;padding-top: 2px;  "> 
<a   href="<?php echo LANG_URL ?><?php echo (trim($toppage2->pagurl)?'vacations/'.trim($toppage2->pagurl):'item/v/i/'.$toppage2->id) ?>" > More >>   </a> </div>
<div style="text-align:left; color:#28272F;height: 27px;padding-top: 2px; ">  
 <?php echo $toppage2->ptdpage; ?>   </div>
</div>
							</article>
                           
						</div>
                        
                      
                        <?php endif; ?> 
 
                        <?php endforeach; ?>








<!--  //////////////////////////////////////////////////////////// -->


 <?php
 
								$model = new Model_PlusData();
						        $model->_name  = 'items';						                                       
						        $toppages2 = $model->selectForArray(array('countryid5' => $value->id , 'inactive' => '0'), array('displayorder' => 'ASC')  );
								foreach($toppages2 as $toppage2):
									   
							?>  

    <?php if( $toppage2->regionid5 != '0'): ?> 
          <div class="item col-sm-4">
                                             
							<article class="place-box card">
					 <?php
 
								$model = new Model_PlusData();
						        $model->_name  = 'label';						                                       
						        $toppages27 = $model->selectForArray(array('id' => $toppage2->labelid), array('displayorder' => 'ASC') , 1 );
								foreach($toppages27 as $toppage27):
									   
							?>  		
							
    <img  style="position:absolute" src="<?php echo  APP_BASEURL.'/MyUpload/'.$toppage27->image ?>"  width="96" height="91" border="0" class="corner">
	<?php endforeach; ?>
	
	
								<a href="<?php echo LANG_URL ?><?php echo (trim($toppage2->pagurl)?'vacations/'.trim($toppage2->pagurl):'item/v/i/'.$toppage2->id) ?>" class="">
									 
									<div class="entry-thumbnail"> 
		 <img style="margin-right:10px;" width="400" height="250"  style="margin-right:10px;"   src="<?php echo  APP_BASEURL.'/MyUpload/'.$toppage2->thumb ?>">

 				
 
 </div>
							  </a>
                              <div style="padding: 1px 15px 4px; z-index: 1; bottom: 0;background: #f2f2f2;border-radius: 0 0 6px 6px;">
                              <h3 class="headerrr" ><a href="<?php echo LANG_URL ?><?php echo (trim($toppage2->pagurl)?'vacations/'.trim($toppage2->pagurl):'item/v/i/'.$toppage2->id) ?>" ><?php echo $toppage2->title; ?> </a> </h3>
                              <div class="blockpackagehome" > <?php echo $toppage2->shortdescription; ?>  </div>
                           <div style="border-bottom:1px solid #d0d0d0; padding-bottom:30px;">   
<?php echo $toppage2->daynumber; ?> days
<?php if(trim($toppage2->prize2)): ?>

<spam style="color:#dc1f26;"> From </spam>	    
<spam <?php if(trim($toppage2->newprice2)): ?><?php echo 'style="color:#dc1f26;text-decoration: line-through;" ' ?> <?php elseif(!trim($toppage2->newprice2)): ?><?php echo 'style="color:#dc1f26;" ' ?><?php endif; ?>  >  $<?php echo number_format($toppage2->prize2) ?>  </spam>
<?php if(trim($toppage2->newprice2)): ?>  <spam style="color:#dc1f26; padding-left:8px;" >   $<?php echo number_format($toppage2->newprice2); ?>  </spam> <?php endif; ?><?php endif; ?>  <br/> 



<?php echo $toppage2->pricedescription; ?>  </div>
<div style="text-align:right; float:right;padding-top: 2px;  "> 
<a   href="<?php echo LANG_URL ?><?php echo (trim($toppage2->pagurl)?'vacations/'.trim($toppage2->pagurl):'item/v/i/'.$toppage2->id) ?>" > More >>   </a> </div>
<div style="text-align:left; color:#28272F;height: 27px;padding-top: 2px; ">  
 <?php echo $toppage2->ptdpage; ?>   </div>
</div>
							</article>
                           
						</div>
                        
                      
                        <?php endif; ?> 
 
                        <?php endforeach; ?>
















<!--  //////////////////////////////////////////////////////////// -->


 <?php
 
								$model = new Model_PlusData();
						        $model->_name  = 'items';						                                       
						        $toppages2 = $model->selectForArray(array('countryid6' => $value->id , 'inactive' => '0'), array('displayorder' => 'ASC')  );
								foreach($toppages2 as $toppage2):
									   
							?>  

    <?php if( $toppage2->regionid6 != '0'): ?> 
          <div class="item col-sm-4">
                                             
							<article class="place-box card">
					 <?php
 
								$model = new Model_PlusData();
						        $model->_name  = 'label';						                                       
						        $toppages27 = $model->selectForArray(array('id' => $toppage2->labelid), array('displayorder' => 'ASC') , 1 );
								foreach($toppages27 as $toppage27):
									   
							?>  		
							
    <img  style="position:absolute" src="<?php echo  APP_BASEURL.'/MyUpload/'.$toppage27->image ?>"  width="96" height="91" border="0" class="corner">
	<?php endforeach; ?>
	
	
								<a href="<?php echo LANG_URL ?><?php echo (trim($toppage2->pagurl)?'vacations/'.trim($toppage2->pagurl):'item/v/i/'.$toppage2->id) ?>" class="">
									 
									<div class="entry-thumbnail"> 
		 <img style="margin-right:10px;" width="400" height="250"  style="margin-right:10px;"   src="<?php echo  APP_BASEURL.'/MyUpload/'.$toppage2->thumb ?>">

 				
 
 </div>
							  </a>
                              <div style="padding: 1px 15px 4px; z-index: 1; bottom: 0;background: #f2f2f2;border-radius: 0 0 6px 6px;">
                              <h3 class="headerrr" ><a href="<?php echo LANG_URL ?><?php echo (trim($toppage2->pagurl)?'vacations/'.trim($toppage2->pagurl):'item/v/i/'.$toppage2->id) ?>" ><?php echo $toppage2->title; ?> </a> </h3>
                              <div class="blockpackagehome" > <?php echo $toppage2->shortdescription; ?>  </div>
                           <div style="border-bottom:1px solid #d0d0d0; padding-bottom:30px;">  
 <?php echo $toppage2->daynumber; ?> days 
<?php if(trim($toppage2->prize2)): ?>

<spam style="color:#dc1f26;"> From </spam>	    
<spam <?php if(trim($toppage2->newprice2)): ?><?php echo 'style="color:#dc1f26;text-decoration: line-through;" ' ?> <?php elseif(!trim($toppage2->newprice2)): ?><?php echo 'style="color:#dc1f26;" ' ?><?php endif; ?>  >  $<?php echo number_format($toppage2->prize2) ?>  </spam>
<?php if(trim($toppage2->newprice2)): ?>  <spam style="color:#dc1f26; padding-left:8px;" >   $<?php echo number_format($toppage2->newprice2); ?>  </spam> <?php endif; ?><?php endif; ?>  <br/> 



<?php echo $toppage2->pricedescription; ?> </div>
<div style="text-align:right; float:right;padding-top: 2px;  "> 
<a   href="<?php echo LANG_URL ?><?php echo (trim($toppage2->pagurl)?'vacations/'.trim($toppage2->pagurl):'item/v/i/'.$toppage2->id) ?>" > More >>   </a> </div>
<div style="text-align:left; color:#28272F;height: 27px;padding-top: 2px; ">  
 <?php echo $toppage2->ptdpage; ?>   </div>
</div>
							</article>
                           
						</div>
                        
                      
                        <?php endif; ?> 
 
                        <?php endforeach; ?>



<!--  //////////////////////////////////////////////////////////// -->


 <?php
 
								$model = new Model_PlusData();
						        $model->_name  = 'items';						                                       
						        $toppages2 = $model->selectForArray(array('countryid7' => $value->id , 'inactive' => '0'), array('displayorder' => 'ASC')  );
								foreach($toppages2 as $toppage2):
									   
							?>  

    <?php if( $toppage2->regionid7 != '0'): ?> 
          <div class="item col-sm-4">
                                             
							<article class="place-box card">
					 <?php
 
								$model = new Model_PlusData();
						        $model->_name  = 'label';						                                       
						        $toppages27 = $model->selectForArray(array('id' => $toppage2->labelid), array('displayorder' => 'ASC') , 1 );
								foreach($toppages27 as $toppage27):
									   
							?>  		
							
    <img  style="position:absolute" src="<?php echo  APP_BASEURL.'/MyUpload/'.$toppage27->image ?>"  width="96" height="91" border="0" class="corner">
	<?php endforeach; ?>
	
	
								<a href="<?php echo LANG_URL ?><?php echo (trim($toppage2->pagurl)?'vacations/'.trim($toppage2->pagurl):'item/v/i/'.$toppage2->id) ?>" class="">
									 
									<div class="entry-thumbnail"> 
		 <img style="margin-right:10px;" width="400" height="250"  style="margin-right:10px;"   src="<?php echo  APP_BASEURL.'/MyUpload/'.$toppage2->thumb ?>">

 				
 
 </div>
							  </a>
                              <div style="padding: 1px 15px 4px; z-index: 1; bottom: 0;background: #f2f2f2;border-radius: 0 0 6px 6px;">
                              <h3 class="headerrr" ><a href="<?php echo LANG_URL ?><?php echo (trim($toppage2->pagurl)?'vacations/'.trim($toppage2->pagurl):'item/v/i/'.$toppage2->id) ?>" ><?php echo $toppage2->title; ?> </a> </h3>
                              <div class="blockpackagehome" > <?php echo $toppage2->shortdescription; ?>  </div>
                           <div style="border-bottom:1px solid #d0d0d0; padding-bottom:30px;">   
<?php echo $toppage2->daynumber; ?> days <?php if(trim($toppage2->prize2)): ?>

<spam style="color:#dc1f26;"> From </spam>	    
<spam <?php if(trim($toppage2->newprice2)): ?><?php echo 'style="color:#dc1f26;text-decoration: line-through;" ' ?> <?php elseif(!trim($toppage2->newprice2)): ?><?php echo 'style="color:#dc1f26;" ' ?><?php endif; ?>  >  $<?php echo number_format($toppage2->prize2) ?>  </spam>
<?php if(trim($toppage2->newprice2)): ?>  <spam style="color:#dc1f26; padding-left:8px;" >   $<?php echo number_format($toppage2->newprice2); ?>  </spam> <?php endif; ?><?php endif; ?>  <br/> 



<?php echo $toppage2->pricedescription; ?> </div>
<div style="text-align:right; float:right;padding-top: 2px;  "> 
<a   href="<?php echo LANG_URL ?><?php echo (trim($toppage2->pagurl)?'vacations/'.trim($toppage2->pagurl):'item/v/i/'.$toppage2->id) ?>" > More >>   </a> </div>
<div style="text-align:left; color:#28272F;height: 27px;padding-top: 2px; ">  
 <?php echo $toppage2->ptdpage; ?>   </div>
</div>
							</article>
                           
						</div>
                        
                      
                        <?php endif; ?> 
 
                        <?php endforeach; ?>



                          
       
                         
                         
						 
					</div>
				</div>
			</div>
		</section>

  <section class="">
			<div class="container">
             <div class="col-sm-5"><h2>Know before you go </h2> </div>
             <div class="col-sm-7" style="text-align: right;padding-top: 20px;"> 
			 <?php if(trim($value->image)): ?> 
			<a style="text-decoration:none" href="<?php echo  APP_BASEURL.'/MyUpload/'.$value->image ?> " download >  <h4 style="color:#000000">Download <?php echo $value->data; ?> Travel info <img   title="" src="<?php echo THEME_DIR ?>assets/images/download.png"></h4>  </a> 
			<?php endif; ?>
			 
			 
			 </div>
             
			 
			 
              <div class="col-sm-12 " style="padding-bottom:120px; padding-top:20px;">
              
               <span style="width:100%" class="  teaser">
              <?php echo $value->shortdata; ?>
			  </span>

<span class="complete">  
  <?php echo $value->longdata; ?>


</span>
<?php if(trim($value->longdata)): ?>
<span class="more">More...</span>
<?php endif; ?>


 </div>
 

</div></section>

<script>
// When the user scrolls down 20px from the top of the document, show the button
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
    if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
        document.getElementById("myBtn").style.display = "block";
    } else {
        document.getElementById("myBtn").style.display = "none";
    }
}

// When the user clicks on the button, scroll to the top of the document
function topFunction() {
    document.body.scrollTop = 0;
    document.documentElement.scrollTop = 0;
}
</script>


 
       



 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script> 
        <script   src="https://code.jquery.com/jquery-1.5.2.js" ></script>
 
 <script  language="javascript">
 $(".more").toggle(function(){
    $(this).text("Less..").siblings(".complete").show();    
}, function(){
    $(this).text("more..").siblings(".complete").hide();    
});

</script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
 
 <?php endforeach ?>