<style>
.fc-icon:after{
display:none !important; 
}
</style>
	<!-- Page header -->
			<div class="page-header page-header-light">
				<div class="page-header-content header-elements-md-inline">
					<div class="page-title d-flex">
						<h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">Tasks </span>  </h4>
						<a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
					</div>

					<div class="header-elements d-none">
						<div class="d-flex justify-content-center">

						  	</div>
					</div>
				</div>

				<div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
					<div class="d-flex">
						<div class="breadcrumb">
							<a href="<?php echo $this->baseUrl() ?>/admin" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
							<span class="breadcrumb-item active">Dashboard</span>
						</div>
 
					</div>

					<div class="header-elements d-none">
						<div class="breadcrumb justify-content-center">
 
 
						 
						</div>
					</div>
				</div>
			</div>
			<!-- /page header -->



  <div class="content">

				<!-- Form inputs -->
				<div class="card" style="padding:10px;" >




 <div class="col-md-12" style="margin: 0px 0px 30px 0px;background: ;padding-top: 10px;" >
 
<h4> Add New Task </h4>
<form   id="form3" name="form3" method="post" action="<?php echo  $this->baseUrl().'/admin/'.'Calendar' ?>"     enctype="multipart/form-data"   >
<input id="userid" type="hidden" name="userid"  value="">

 <div class="col-md-12" style="float:left;padding-top:20px;" ><input class="form-control" name="Title" placeholder="Title" value=""></div> 
 <div class="col-md-12" style="float:left;padding-top:20px;" ><textarea class="form-control" name="Details" cols="" rows="" placeholder="Details" ></textarea> </div> 
 <div class="col-md-3" style="float:left;padding-top:20px;"  ><input required type="text"  class="form-control datepicker" placeholder="From"  id="DateFrom" name="DateFrom" class="form-control  hasDatepicker" value=""> </div>
 <div class="col-md-3" style="float:left;padding-top:20px;"  ><input  type="text" class="form-control datepicker" placeholder="To" name="DateTo" id="DateTo" data-format="yyyy-mm-dd" value=""> </div> 

 
<div class="col-md-2" style="float:right" >
<input type="submit" name="savetask" id="savetask" value="Save" class="btn btn-primary" style="margin:20px"></div>
 </form>
</div>
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
  
  $( function() {
    $( "#DateFrom" ).datepicker({ dateFormat: 'yy-mm-dd' });
    $( "#DateTo" ).datepicker({ dateFormat: 'yy-mm-dd' });
  } );
 
  </script>

     <link rel="stylesheet" type="text/css" href="<?php echo $this->themeUrl ?>app-assets/vendors/css/calendars/fullcalendar.min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $this->themeUrl ?>app-assets/vendors/css/calendars/extensions/daygrid.min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $this->themeUrl ?>app-assets/vendors/css/calendars/extensions/timegrid.min.css">
     <!-- END: Vendor CSS-->
   <!-- BEGIN: Theme CSS-->
 
   
    <!-- BEGIN: Theme CSS-->
 
    <link rel="stylesheet" type="text/css" href="<?php echo $this->themeUrl ?>app-assets/css/plugins/calendars/fullcalendar.css">

 <div class="approch-area pd-20px">
       <div class="container">
           <div class="row">
               <div class="col-lg-12">

   <!-- BEGIN: Content-->
    <div class="app-content content">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class=" ">
            <div class="content-header row">
            </div>
            <div class="content-body">
                <!-- Full calendar start -->
                <section style="padding:0px;" >
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-content">
                                    <div class="card-body">
                                      
                                        <div id='fc-default'></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- calendar Modal starts-->
                    <div class="modal fade text-left modal-calendar" tabindex="-1" role="dialog" aria-labelledby="cal-modal" aria-modal="true">
                        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-sm" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title text-text-bold-600" id="cal-modal"> </h4>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">×</span>
                                    </button>
                                </div>
                                <form action="#">
                                    <div class="modal-body">
 
                                    
 <fieldset id="cal-modal2"  class="form-label-group" style="margin-bottom:0px;">
 </fieldset>

 
 
                                        
 
 <fieldset class="form-label-group">
 <div  style="float: left; margin-left: 15px;" id="cal-description" ></div>
 </fieldset>
                                    </div>
                                    <div class="modal-footer">
                                        
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <!-- calendar Modal ends-->
                </section>
                <!-- // Full calendar end -->
<script>

 /*=========================================================================================
    File Name: fullcalendar.js
 
    --------------------------------------------------------------------------------------
    Item Name: Vuexy  - Vuejs, HTML & Laravel Admin Dashboard Template
    Version: 2.0
    Author: PIXINVENT
    Author URL: http://www.themeforest.net/user/pixinvent
==========================================================================================*/

document.addEventListener('DOMContentLoaded', function () {

  // color object for different event types
  var colors = {
    primary: "#7367f0",
    success: "#28c76f",
    danger: "#ea5455",
    warning: "#ff9f43"
  };

  // chip text object for different event types
  var categoryText = {
    primary: "Others",
    success: "Business",
    danger: "Personal",
    warning: "Work"
  };
  var categoryBullets = $(".cal-category-bullets").html(),
    evtColor = "",
    eventColor = "";

  // calendar init
  var calendarEl = document.getElementById('fc-default');

  var calendar = new FullCalendar.Calendar(calendarEl, {
    plugins: ["dayGrid", "timeGrid", "interaction"],
    
    header: {
      left: "dayGridMonth,timeGridWeek,timeGridDay",
      right: "prev,title,next"
    },
    displayEventTime: false,
    navLinks: true,
    editable: true,
    allDay: true,
    navLinkDayClick: function (date) {
      //$(".modal-calendar").modal("show");
    },
    dateClick: function (info) {
      $(".modal-calendar #cal-start-date").val(info.dateStr).attr("disabled", true);
      $(".modal-calendar #cal-end-date").val(info.dateStr);
    },
    // displays saved event values on click
    eventClick: function (info) {
   
if(info.event.extendedProps.description == '  '){
  $(".modal-calendar").modal("hide");
}
else{
      $(".modal-calendar").modal("show");
}
      $(".modal-calendar #cal-event-title").val(info.event.title);
      document.getElementById("cal-modal").innerHTML = info.event.extendedProps.title2;
      document.getElementById("cal-modal2").innerHTML = info.event.extendedProps.description;
      $(".modal-calendar #cal-start-date").val(moment(info.event.start).format('dddd MMMM D , Y'));
      $(".modal-calendar #cal-end-date").val(info.event.end);
 
if(info.event.extendedProps.location2 != 0){
       document.getElementById("cal-time").innerHTML = '<i style="    padding-right: 10px;margin-top: 4px;color:#000;font-size:17px; float:left;" class="fa fa-clock-o" aria-hidden="true"></i> '+info.event.extendedProps.location2 
}
else{
      document.getElementById("cal-time").innerHTML = '' ;
}


 
       document.getElementById("cal-description").innerHTML = info.event.extendedProps.description

      $(".modal-calendar .cal-submit-event").removeClass("d-none");
      $(".modal-calendar .remove-event").removeClass("d-none");
      $(".modal-calendar .cal-add-event").addClass("d-none");
      $(".modal-calendar .cancel-event").addClass("d-none");
      $(".calendar-dropdown .dropdown-menu").find(".selected").removeClass("selected");
      var eventCategory = info.event.extendedProps.dataEventColor;
      var eventText = categoryText[eventCategory]
      $(".modal-calendar .chip-wrapper .chip").remove();
      $(".modal-calendar .chip-wrapper").append($("<div class='chip chip-" + eventCategory + "'>" +
        "<div class='chip-body'>" +
        "<span class='chip-text'> " + eventText + " </span>" +
        "</div>" +
        "</div>"));
    },
  });

  // render calendar
  calendar.render();

  // appends bullets to left class of header
  $("#basic-examples .fc-right").append(categoryBullets);

  // Close modal on submit button
  $(".modal-calendar .cal-submit-event").on("click", function () {
    $(".modal-calendar").modal("hide");
  });

  // Remove Event
  $(".remove-event").on("click", function () {
    var removeEvent = calendar.getEventById('newEvent');
    removeEvent.remove();
  });


  // reset input element's value for new event
  if ($("td:not(.fc-event-container)").length > 0) {
    $(".modal-calendar").on('hidden.bs.modal', function (e) {
      $('.modal-calendar .form-control').val('');
    })
  }

  // remove disabled attr from button after entering info
  $(".modal-calendar .form-control").on("keyup", function () {
    if ($(".modal-calendar #cal-event-title").val().length >= 1) {
      $(".modal-calendar .modal-footer .btn").removeAttr("disabled");
    }
    else {
      $(".modal-calendar .modal-footer .btn").attr("disabled", true);
    }
  });

  // open add event modal on click of day
  $(document).on("click", ".fc-day", function () {
    //$(".modal-calendar").modal("show");
    $(".calendar-dropdown .dropdown-menu").find(".selected").removeClass("selected");
    $(".modal-calendar .cal-submit-event").addClass("d-none");
    $(".modal-calendar .remove-event").addClass("d-none");
    $(".modal-calendar .cal-add-event").removeClass("d-none");
    $(".modal-calendar .cancel-event").removeClass("d-none");
    $(".modal-calendar .add-category .chip").remove();
    $(".modal-calendar .modal-footer .btn").attr("disabled", true);
    evtColor = colors.primary;
    eventColor = "primary";
  });

  // change chip's and event's color according to event type
  $(".calendar-dropdown .dropdown-menu .dropdown-item").on("click", function () {
    var selectedColor = $(this).data("color");
    evtColor = colors[selectedColor];
    eventTag = categoryText[selectedColor];
    eventColor = selectedColor;

    // changes event color after selecting category
    $(".cal-add-event").on("click", function () {
      calendar.addEvent({
        color: evtColor,
        dataEventColor: eventColor,
        className: eventColor
      });
    })

    $(".calendar-dropdown .dropdown-menu").find(".selected").removeClass("selected");
    $(this).addClass("selected");

    // add chip according to category
    $(".modal-calendar .chip-wrapper .chip").remove();
    $(".modal-calendar .chip-wrapper").append($("<div class='chip chip-" + selectedColor + "'>" +
      "<div class='chip-body'>" +
      "<span class='chip-text'> " + eventTag + " </span>" +
      "</div>" +
      "</div>"));
  });

  // calendar add event
 
 	
 <?php $model = new Model_PlusData();    $model->_name  = 'Tasks';     
						        $toppages1 = $model->selectForArray( array(), array('title' => 'ASC')  );
								foreach($toppages1 as $events):	?>

    $(".modal-calendar").modal("hide");
  var eventTitle = '<?php echo $events->Title; ?>',
      eventTitle2 = "Task",
      startDate = "<?php echo $events->DateFrom; ?>",
      endDate = "<?php echo $events->DateTo; ?>",
      eventLocation = "1",
      eventDescription = "<?php echo $events->Details; ?>",
      correctEndDate = endDate;


      calendar.addEvent({
      id: "newEvent",
      title: eventTitle,
      title2: eventTitle2,
      start: startDate,
      end: correctEndDate,
      location: eventLocation,
      description: eventDescription,
      color: '#000',
      dataEventColor: eventColor,
      allDay: true
    });
	
	<?php endforeach; ?>

  // date picker
  $(".pickadate").pickadate({
    format: 'yyyy-mm-dd'
  });
});

 </script>
            </div>
        </div>
    </div>
    <!-- END: Content-->
</div></div></div></div>

   <!-- BEGIN: Vendor JS-->
    <script src="<?php echo $this->themeUrl ?>app-assets/vendors/js/vendors.min.js"></script>
    <!-- BEGIN Vendor JS-->

    <!-- BEGIN: Page Vendor JS-->
      <script src="<?php echo $this->themeUrl ?>app-assets/vendors/js/calendar/fullcalendar.min.js"></script>
    <script src="<?php echo $this->themeUrl ?>app-assets/vendors/js/calendar/extensions/daygrid.min.js"></script>
    <script src="<?php echo $this->themeUrl ?>app-assets/vendors/js/calendar/extensions/timegrid.min.js"></script>
    <script src="<?php echo $this->themeUrl ?>app-assets/vendors/js/calendar/extensions/interactions.min.js"></script>
    <!-- END: Theme JS-->
     <script src="<?php echo $this->themeUrl ?>app-assets/js/scripts/extensions/fullcalendar.js"></script>
 

</div></div>