 
		
	 
 
  <style type="text/css">
<!--
.style1 {color: #828283}
.style2 {color: #2181c4}
-->

.complete{
    display:none;
}

.more{
       background: #f9b017;
    color: navy;
    font-size: 16px;
   
    cursor: pointer;
    padding: 10px;
    color: #fff;
    float: right;
    margin-right: 10px;
}


</style>


<style>
#myBtn {
  display: none;
  position: fixed;
  bottom: 35px;
  right: 30px;
  z-index: 99;
  border: none;
  outline: none;
  background-color: #124273 ;
  color: white;
  cursor: pointer;
  padding: 12px;
  border-radius: 10px;
}

#myBtn:hover {
  background-color: #f9b017;
}
</style>

 
	<!-- Hero Section
		================================================== -->
		<section class="hero small-hero" >
			<div class="bg-overlay">
				<div class="container" style="">
					  
			  </div>
			</div>
		</section>


		<!-- Main Section
		================================================== -->
        
        <section class="">
			<div class="container">


             <div class="col-sm-12" style="text-align:center" >
<img  style="margin-bottom: 40px;margin-top: 40px;" src="<?php echo THEME_DIR ?>assets/images/error.jpg">

</div> </div></section>
 