<?php  $url = $this->baseUrl().'/admin/'; ?>
<script>
function confdelete(url)
                {
                    var fRet;
                    fRet = confirm('Are You Sure You Want Delete ?');
                    if(fRet == true){
                       window.location = url;
                    }}
</script>
<?php  
$this->session = new Zend_Session_Namespace('Default');
 $auth = Zend_Auth::getInstance();
        if($auth->hasIdentity()) {
$userInfo = Zend_Auth::getInstance()->getStorage()->read();
 $userid =  $userInfo->id;
 }
 

  ?>

<?php
$this->session = new Zend_Session_Namespace('Default');
$request = Zend_Controller_Front::getInstance()->getRequest()->getRequestUri();
 $auth = Zend_Auth::getInstance();
        if($auth->hasIdentity()) {
$userInfo = Zend_Auth::getInstance()->getStorage()->read();
 $userid =  $userInfo->id;
} ?>
<?php  $allpermissionsmain = array() ;  $allpermission = array() ; 	$model = new Model_PlusData();
			 $model->_name  = 'users';						                                       
			 $toppages2item = $model->selectForArray(array('id' => $userid ), array('displayorder' => 'ASC') , 1  );
								foreach($toppages2item as $User):?> 

 <?php  $allpermission = array() ; $all = explode('||',trim($User->permissions ,'|')); foreach($all as $photo): ?>
<?php $allpermission []= $photo ?> <?php endforeach; ?> 
 <?php  $allpermissionsmain = array() ; $all2 = explode('||',trim($User->allpermissionsmain ,'|')); foreach($all2 as $photo2): ?>
<?php $allpermissionsmain []= $photo2 ?> <?php endforeach; ?>
		 	 
   <?php endforeach; ?>

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Admin - Tidal</title>

	<!-- Global stylesheets -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
	<link href="<?php echo $this->themeUrl ?>global_assets/css/icons/icomoon/styles.min.css" rel="stylesheet" type="text/css">
	<link href="<?php echo $this->themeUrl ?>assets/css/bootstrap.min.php?ButtonColor=<?php echo  $User->ButtonColor; ?>" rel="stylesheet" type="text/css">
	<link href="<?php echo $this->themeUrl ?>assets/css/bootstrap_limitless.min.php?TopMenuColor=<?php echo  $User->TopMenuColor; ?>" rel="stylesheet" type="text/css">
	<link href="<?php echo $this->themeUrl ?>assets/css/layout.min.php?LeftSlideColor=<?php echo  $User->LeftSlideColor; ?>" rel="stylesheet" type="text/css">
	<link href="<?php echo $this->themeUrl ?>assets/css/components.min.css" rel="stylesheet" type="text/css">
	<link href="<?php echo $this->themeUrl ?>assets/css/colors.min.css" rel="stylesheet" type="text/css">
	<!-- /global stylesheets -->

	<!-- Core JS files -->
	<script src="<?php echo $this->themeUrl ?>global_assets/js/main/jquery.min.js"></script>
	<script src="<?php echo $this->themeUrl ?>global_assets/js/main/bootstrap.bundle.min.js"></script>
	<script src="<?php echo $this->themeUrl ?>global_assets/js/plugins/loaders/blockui.min.js"></script>
	<!-- /core JS files -->

	<!-- Theme JS files -->
	<script src="<?php echo $this->themeUrl ?>global_assets/js/plugins/visualization/d3/d3.min.js"></script>
	<script src="<?php echo $this->themeUrl ?>global_assets/js/plugins/visualization/d3/d3_tooltip.js"></script>
	<script src="<?php echo $this->themeUrl ?>global_assets/js/plugins/forms/styling/switchery.min.js"></script>
	<script src="<?php echo $this->themeUrl ?>global_assets/js/plugins/ui/moment/moment.min.js"></script>
	<script src="<?php echo $this->themeUrl ?>global_assets/js/plugins/pickers/daterangepicker.js"></script>

	<script src="<?php echo $this->themeUrl ?>assets/js/app.js"></script>
	<script src="<?php echo $this->themeUrl ?>global_assets/js/demo_pages/dashboard.js"></script>
	<script src="<?php echo $this->themeUrl ?>global_assets/js/demo_charts/pages/dashboard/light/streamgraph.js"></script>
	<script src="<?php echo $this->themeUrl ?>global_assets/js/demo_charts/pages/dashboard/light/sparklines.js"></script>
	<script src="<?php echo $this->themeUrl ?>global_assets/js/demo_charts/pages/dashboard/light/lines.js"></script>	
	<script src="<?php echo $this->themeUrl ?>global_assets/js/demo_charts/pages/dashboard/light/areas.js"></script>
	<script src="<?php echo $this->themeUrl ?>global_assets/js/demo_charts/pages/dashboard/light/donuts.js"></script>
	<script src="<?php echo $this->themeUrl ?>global_assets/js/demo_charts/pages/dashboard/light/bars.js"></script>
	<script src="<?php echo $this->themeUrl ?>global_assets/js/demo_charts/pages/dashboard/light/progress.js"></script>
	<script src="<?php echo $this->themeUrl ?>global_assets/js/demo_charts/pages/dashboard/light/heatmaps.js"></script>
	<script src="<?php echo $this->themeUrl ?>global_assets/js/demo_charts/pages/dashboard/light/pies.js"></script>
	<script src="<?php echo $this->themeUrl ?>global_assets/js/demo_charts/pages/dashboard/light/bullets.js"></script>
	<!-- /theme JS files -->

	<!-- Theme JS files -->
	<script src="<?php echo $this->themeUrl ?>global_assets/js/plugins/tables/datatables/datatables.min.js"></script>
	<script src="<?php echo $this->themeUrl ?>global_assets/js/plugins/forms/selects/select2.min.js"></script>
	<script src="<?php echo $this->themeUrl ?>global_assets/js/demo_pages/datatables_data_sources.js"></script>
	<script src="<?php echo $this->themeUrl ?>global_assets/js/demo_pages/datatables_advanced.js"></script>
</head>

<body>

	<!-- Main navbar -->
	<div class="navbar navbar-expand-md navbar-dark">
		<div class="navbar-brand" style="padding-top:4px; padding-bottom:4px;" >
			<a href="index" class="d-inline-block">
<h2 style="color:#fff;" >Tidal</h3>
 
			</a>
		</div>

		<div class="d-md-none">
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-mobile">
				<i class="icon-tree5"></i>
			</button>
			<button class="navbar-toggler sidebar-mobile-main-toggle" type="button">
				<i class="icon-paragraph-justify3"></i>
			</button>
		</div>

		<div class="collapse navbar-collapse" id="navbar-mobile">
			<ul class="navbar-nav">
				<li class="nav-item">
					<a href="#" class="navbar-nav-link sidebar-control sidebar-main-toggle d-none d-md-block">
						<i class="icon-paragraph-justify3"></i>
					</a>
				</li>

				<li class="nav-item dropdown">
				 

					 
				</li>
			</ul>

		 	<span class="badge  ml-md-3 mr-md-auto" style="display: block;" ></span>
			<ul class="navbar-nav">
			 

			 

				<li class="nav-item dropdown dropdown-user">
					<a href="#" class="navbar-nav-link d-flex align-items-center dropdown-toggle" data-toggle="dropdown">
  
						 
						<span> <?php echo $User->firstname.' '.$User->lastname; ?></span>
					</a>

					<div class="dropdown-menu dropdown-menu-right">
					 	<a href="<?php echo $url.'Accountsettings/edit/id/'.$userid.'?id='.$userid ?>" class="dropdown-item"><i class="icon-cog5"></i> Account settings</a>
					
						<a href="<?php echo $this->baseUrl() ?>/admin/index/logout" class="dropdown-item"><i class="icon-switch2"></i> Logout</a>
					</div>
				</li>
			</ul>
		</div>
	</div>
	<!-- /main navbar -->


	<!-- Page content -->
	<div class="page-content">

		<!-- Main sidebar -->
		<div class="sidebar sidebar-dark sidebar-main sidebar-expand-md">

			<!-- Sidebar mobile toggler -->
			<div class="sidebar-mobile-toggler text-center">
				<a href="#" class="sidebar-mobile-main-toggle">
					<i class="icon-arrow-left8"></i>
				</a>
				Navigation
				<a href="#" class="sidebar-mobile-expand">
					<i class="icon-screen-full"></i>
					<i class="icon-screen-normal"></i>
				</a>
			</div>
			<!-- /sidebar mobile toggler -->


			<!-- Sidebar content -->
			<div class="sidebar-content">

				<!-- User menu -->
			 
				<!-- /user menu -->


				<!-- Main navigation -->
				<div class="card card-sidebar-mobile">
					<ul class="nav nav-sidebar" data-nav-type="accordion">

						<!-- Main -->
					 	<li class="nav-item" style="padding-top:0px;" >
							<a  style="background: #a3a3a3;" href="<?php echo $this->baseUrl() ?>/admin/index" class="nav-link active">
								<i class="icon-home4"></i>
								<span>
									Dashboard
								</span>
							</a>
						</li>
				 
						<!-- Forms -->
<?php if(in_array('Setting' , $allpermissionsmain)): ?>

 <li class="nav-item-header"><div class="text-uppercase font-size-xs line-height-xs">Setting</div> <i class="icon-menu" title="Forms"></i></li>
 <li class="nav-item nav-item-submenu">
							<a href="#" class="nav-link"><i class="icon-pencil3"></i> <span>Security</span></a>
							<ul class="nav nav-group-sub" data-submenu-title="Form components">

<!-- <li class="nav-item"> <a href="<?php echo $url.'option/mail' ?>" class="nav-link">Admin Email</a></li> -->
 <?php if(in_array('Users Account_index' , $allpermission)): ?><li class="nav-item"><a href="<?php echo $url.'Users/indexuser' ?>" class="nav-link">Users Account</a></li><?php endif; ?>
 
 <?php if(in_array('Social Icons_index' , $allpermission)): ?><li class="nav-item"><a href="<?php echo $url.'Social/edit/id/1?id=1' ?>" class="nav-link">Social Media <spam style="color:red;" >  </spam></a></li> <?php endif; ?>
   
 

<?php if(in_array('Defaul SEO_index' , $allpermission)): ?> <li class="nav-item"><a href="<?php echo $url.'Defaulseo' ?>" class="nav-link">Home Page & Defaults <spam style="color:red;" >  </spam></a></li><?php endif; ?>
 
					    	</ul>
						</li>
<?php endif; ?>

   
 


 

<?php if(in_array('HomePage' , $allpermissionsmain)): ?>	
						<li class="nav-item nav-item-submenu">
							<a href="#" class="nav-link"><i class="icon-grid6"></i> <span>Home Page</span></a>
							<ul class="nav nav-group-sub" data-submenu-title="JSON forms">
<?php if(in_array('Home Slider_index' , $allpermission)): ?> <li class="nav-item"><a href="<?php echo $url.'Homeslider' ?>" class="nav-link"> Home Slider  </a></li><?php endif; ?>
  <li class="nav-item"><a href="<?php echo $url.'Homepagesection/edit/id/1?id=1' ?>" class="nav-link"> Home Section  </a></li> 
 
 
      						</ul>
						</li>
<?php endif; ?>


 
 
 
   <?php if(in_array('Solutions_index' , $allpermission)): ?>
						<li class="nav-item  ">
							<a href="<?php echo $url.'Servicescategories' ?>" class="nav-link"><i class="icon-stamp"></i>  Solutions<a> 
						</li>
<?php endif; ?>	

 
  <?php if(in_array('Clients_index' , $allpermission)): ?>
						<li class="nav-item  ">
							<a href="<?php echo $url.'Projects' ?>" class="nav-link"><i class="icon-stamp"></i>  Clients<a> 
						</li>
<?php endif; ?>	
 

   
   <?php if(in_array('Blogs Category_index' , $allpermission)): ?>
						<li class="nav-item  ">
							<a href="<?php echo $url.'Blogscategories' ?>" class="nav-link"><i class="icon-stamp"></i> Blogs Category<a> 
 				 
						</li>
<?php endif; ?>	


   
   <?php if(in_array('Blogs_index' , $allpermission)): ?>
						<li class="nav-item  ">
							<a href="<?php echo $url.'Blogs' ?>" class="nav-link"><i class="icon-stamp"></i>  Blogs<a> 
 				 
						</li>
<?php endif; ?>	



 

<?php if(in_array('Pages' , $allpermissionsmain)): ?>		

	<li class="nav-item nav-item-submenu">
							<a href="#" class="nav-link"><i class="icon-folder5"></i> <span>Pages</span></a>
							<ul class="nav nav-group-sub" data-submenu-title="Text editors">
<?php if(in_array('About Us_index' , $allpermission)): ?> <li class="nav-item"><a href="<?php echo $url.'Pages/edit/id/1?id=1' ?>" class="nav-link"> About us </a></li> <?php endif; ?>
 <?php if(in_array('Our Solutions_index' , $allpermission)): ?> <li class="nav-item"><a href="<?php echo $url.'Pages/edit/id/2?id=2' ?>" class="nav-link"> Our Solutions </a></li><?php endif; ?>
<?php if(in_array('Our Clients_index' , $allpermission)): ?> <li class="nav-item"><a href="<?php echo $url.'Pages/edit/id/3?id=3' ?>" class="nav-link"> Our Clients </a></li><?php endif; ?>
    <?php if(in_array('Blogs_index' , $allpermission)): ?> <li class="nav-item"><a href="<?php echo $url.'Pages/edit/id/39?id=39' ?>" class="nav-link"> Blogs </a></li><?php endif; ?>

 <?php if(in_array('Contact Us_index' , $allpermission)): ?> <li class="nav-item"><a href="<?php echo $url.'Pages/edit/id/4?id=4' ?>" class="nav-link"> Contact Us </a></li><?php endif; ?>
 
  <li class="nav-item"><a href="<?php echo $url.'Pages/edit/id/6?id=6' ?>" class="nav-link"> Privacy Policy </a></li>
 
 
 
 
     						</ul>
						</li>
<?php endif; ?>	

 	
  

<?php if(in_array('Requests' , $allpermissionsmain)): ?>
						<li class="nav-item nav-item-submenu">
							<a href="#" class="nav-link"><i class="icon-color-sampler"></i> <span>Requests</span></a>
							<ul class="nav nav-group-sub" data-submenu-title="JSON forms">
<?php if(in_array('Contact Requests_index' , $allpermission)): ?><li class="nav-item"><a href="<?php echo $url.'Contactrequests' ?>" class="nav-link"> Contact Requests  </a></li><?php endif; ?>	
<?php if(in_array('Quote Requests_index' , $allpermission)): ?><li class="nav-item"><a href="<?php echo $url.'Quoterequests' ?>" class="nav-link">Quote Requests  </a></li><?php endif; ?>	
     						</ul>
						</li>
<?php endif; ?>		  

					</ul>
				</div>
				<!-- /main navigation -->












			</div>
			<!-- /sidebar content -->
			
		</div>
		<!-- /main sidebar -->


		<!-- Main content -->
		<div class="content-wrapper">

		
  <?php

                            if ($this->LangBar != 'off') {

                                echo $this->partial('lang.phtml');

                            }

                            ?>
        

                <?php echo $this->FlashMessenger() ?>

            	<?php echo $this->layout()->content?>
		 
			</div>
</div>
			<!-- /content area -->


			<!-- Footer -->
			<div class="navbar navbar-expand-lg navbar-light">
				<div class="text-center d-lg-none w-100">
					<button type="button" class="navbar-toggler dropdown-toggle" data-toggle="collapse" data-target="#navbar-footer">
						<i class="icon-unfold mr-2"></i>
						Footer
					</button>
				</div>

				<div class="navbar-collapse collapse" id="navbar-footer">
					<span class="navbar-text">
					 	
		
					</span>

					<ul class="navbar-nav ml-lg-auto">
					  	</ul>
				</div>
			</div>
			<!-- /footer -->
 

		</div>
		<!-- /main content -->

	</div>
	<!-- /page content -->

</body>
</html>
