 <?php
						$model = new Model_PlusData();
						$model->_name  = 'data_stor';
						$where = array('type' => 'news1');
						$order = array('id'=>'desc');
						$news = $model->selectForArray($where, $order );

						foreach($news as $new):
					?>
				 
				<div class="product-box3" >
					
						<a href="<?php echo LANG_URL ?>page/n/i/<?php echo $new->id ?>">	<h1>	<?php echo $new->title ?></h1> </a>
<span style="font-size:18px;color:#000000; padding-right:10px;"><?php echo $new->dataplus ?></span> <br />
							


<div style="position:relative ; right:10px; top:10px;"><img src="<?php echo THEME_DIR ?>images/xy2.png" width="743" height="18" /> </div>
		 <article2>			 
 
 
  	<?php echo  $new->data  ?>
 
 

</article2> 

	</div><div  style="position:relative ; right:10px" ><img src="<?php echo THEME_DIR ?>images/xy.png" width="743" height="59" /> </div>


						
 

 		<?php endforeach; ?> 