 
<?php  foreach($this->Page as $value) : ?> 
<?php $idid = $value->id; ?>
 
		<div class="page-header">
			<div class="page-header__bg"
				style="background-image: url(<?php echo constant('APP_BASEURL').'/MyUpload/'.$value->id; ?>);"></div>
			<!-- /.page-header__bg -->
			<div class="container">
				<ul class="thm-breadcrumb list-unstyled">
					<li><a href="<?php echo LANG_URL ?>index.php">Home</a></li>
					<li><?php echo $value->Title; ?></li>
				</ul>
				<h2 class="page-header__title"><?php echo $value->Title; ?> </h2><!-- /.page-header__title -->
			</div><!-- /.container -->
		</div><!-- /.page-header -->

<?php endforeach; ?>





 
<section class="about-four section-padding--top" style="margin-bottom:80px;" >
			<div class="container">
				<div class="row gutter-y-60">
				 <div class="col-lg-6">
						<div class="about-four__image" style="width: 90%;">
							<img  style="width: 100%;" src="<?php echo constant('APP_BASEURL').'/MyUpload/'.$value->Thumb; ?>" class="wow fadeInUp"
								data-wow-duration="1500ms" >
						</div>
					</div>  
					<div class="col-lg-6">
						<div class="">
							<div class="section-title "> 
								<h2 class="section-title__title"><?php echo $value->Title; ?></h2><!-- /.section-title__title -->
							</div><!-- /.section-title -->
							<div class="about-four__text"><?php echo $value->description; ?></div>
						 
						</div><!-- /.about-four__content -->
					</div><!-- /.col-lg-6 -->
				</div><!-- /.row -->
			</div><!-- /.container -->
		</section>
  
 
