 <?php foreach($this->Page as $value): ?>

  
    <!--breadcumb area start -->
        <div class="breadcumb-area breadcumb-2 overlay pos-rltv" style="background-image:url(<?php echo constant('APP_BASEURL').'/MyUpload/'.$value->Header; ?>);    background-size: cover;">
            <div class="bread-main">
                <div class="bred-hading text-center">
                    <h5><?php echo $value->title; ?></h5> </div>
                <ol class="breadcrumb">
                    <li class="home"><a title="Go to Home Page" href="<?php echo LANG_URL ?>">Home</a></li>
                    <li class="active"><?php echo $value->title; ?></li>
                </ol>
            </div>
        </div>
        <!--breadcumb area end -->
		
 <style>
 .about-des ul li {
      display: revert;
    margin-left: 20px;
    list-style: square;
	font-size: 16px;
 }
 </style>
 
 
 
 
<div class="about-us-area ptb-40">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <div class="heading-title heading-style pos-rltv mb-20 text-center">
                            <h5 class="uppercase"><?php echo $value->title; ?></h5>
                        </div>
                    </div>
                    <div class="about-us-wrap row">
                    
                        <div class="col-lg-12">
                            <div class="about-des">
                                <p><?php echo $value->Data; ?></p>
                               
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
		
		
		
		
		
		
		
	<div class="shop-main-area pt-0 pb-40">
            <div class="container">
                <div class="row">	
		
		<div class="col-lg-12 col-md-12 order-lg-12 order-md-2">
                       <div class="row"> 
 <?php  $model = new Model_PlusData();  $model->_name  = 'products'; $Produts = $model->selectForArray(array( 'catid' => ($value->id) ), array( 'displayorder' => 'ASC')   );  foreach($Produts as $Produt): ?>
 
                            <div class="col-lg-4">
                                <div class="single-blog sb-2 mb-30">
                                    <div class="blog-img pos-rltv product-overlay">
 <a href="<?php echo LANG_URL ?><?php echo (trim($Produt->pagurl)?'product/'.trim($Produt->pagurl):'product/v/i/'.$Produt->id) ?>"><img src="<?php echo constant('APP_BASEURL').'/MyUpload/'.$Produt->Thumb; ?>" ></a>
                                    </div>
                                    <div class="blog-content">
                                        <div class="blog-title">
                                            <h5 class="uppercase font-bold"><a href="<?php echo LANG_URL ?><?php echo (trim($Produt->pagurl)?'product/'.trim($Produt->pagurl):'product/v/i/'.$Produt->id) ?>"><?php echo $Produt->title; ?> </a></h5>
                                         
                                            <div class="like-comments-date">
 <a href="<?php echo LANG_URL ?><?php echo (trim($Produt->pagurl)?'product/'.trim($Produt->pagurl):'product/v/i/'.$Produt->id) ?>" class="btn-def small" tabindex="0">More Details</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <?php endforeach; ?>
                            
                            
                             
                        </div>
                    </div>
     </div>    </div>    </div>
 
  
 <?php endforeach ?>